// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "payment",
    packageName: "@rms/payment",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "eventing",
        packageName: "@bop/eventing",
        layer: "BOP",
      },
      {
        moduleName: "feature-control",
        packageName: "@bop/feature-control",
        layer: "BOP",
      },
      {
        moduleName: "task",
        packageName: "@bop/task",
        layer: "BOP",
      },
      {
        moduleName: "ordering",
        packageName: "@rms/ordering",
        layer: "RMS",
      },
      {
        moduleName: "pricing",
        packageName: "@rms/pricing",
        layer: "RMS",
      },
    ],
    consumedEvents: ["rms.payment.payment-failed.v1", "rms.payment.payment-succeeded.v1"],
    publishedEvents: ["rms.payment.payment-failed.v1", "rms.payment.payment-succeeded.v1"],
    ownedDatabase: {
      schema: "rms_payment",
      tables: [
        "payment_intent",
        "payment_attempt",
        "payment_intent_operation_record",
        "payment_provider_observation",
        "payment_reconciliation_exception",
        "payment_reconciliation_record",
        "payment_reconciliation_run",
        "payment_terminal_fact",
        "payment_status_projection",
        "provider_webhook_record",
        "provider_webhook_raw_evidence",
        "provider_webhook_processing_record",
      ],
    },
    ownedJobs: ["payment-reconciliation", "payment-terminal-capture-watchdog"],
    featureFlags: [],
    killSwitches: ["payment.provider.admission"],
    piiClassification: {
      classes: ["indirect_identifier", "payment"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Payment Engineering Owner",
    },
  } as const;

/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
