// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "payment",
    packageName: "@rms/payment",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "ordering",
        packageName: "@rms/ordering",
        layer: "RMS",
      },
      {
        moduleName: "pricing",
        packageName: "@rms/pricing",
        layer: "RMS",
      },
    ],
    consumedEvents: [],
    publishedEvents: [],
    ownedDatabase: {
      schema: "rms_payment",
      tables: [
        "payment_intent",
        "payment_attempt",
        "payment_intent_operation_record",
        "payment_provider_observation",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier", "payment"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Payment Engineering Owner",
    },
  } as const;

/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
