// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "ordering",
    packageName: "@rms/ordering",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "eventing",
        packageName: "@bop/eventing",
        layer: "BOP",
      },
      {
        moduleName: "identity",
        packageName: "@bop/identity",
        layer: "BOP",
      },
      {
        moduleName: "catalog",
        packageName: "@rms/catalog",
        layer: "RMS",
      },
      {
        moduleName: "pricing",
        packageName: "@rms/pricing",
        layer: "RMS",
      },
      {
        moduleName: "store",
        packageName: "@rms/store",
        layer: "RMS",
      },
    ],
    consumedEvents: [
      "rms.ordering.order-created.v1",
      "rms.payment.payment-failed.v1",
      "rms.payment.payment-succeeded.v1",
    ],
    publishedEvents: ["rms.ordering.order-confirmed.v1", "rms.ordering.order-created.v1"],
    ownedDatabase: {
      schema: "rms_ordering",
      tables: [
        "cart",
        "cart_line",
        "cart_operation_record",
        "cart_quote_attachment",
        "cart_quote_attachment_line",
        "cart_lifecycle_operation_record",
        "order_number_counter",
        "order_number_allocation",
        "order_header",
        "order_submission_record",
        "order_batch",
        "order_item",
        "order_status_projection_generation",
        "order_status_projection",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier", "personal", "health"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Ordering Engineering Owner",
    },
  } as const;

/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
