// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "ordering",
    packageName: "@rms/ordering",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [],
    consumedEvents: [],
    publishedEvents: [],
    ownedDatabase: {
      schema: "rms_ordering",
      tables: ["cart", "cart_line"],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Ordering Engineering Owner",
    },
  } as const;

/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
