const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "membership", packageName: "@bop/membership", layer: "BOP" },
  tables: [
    {
      table: "membership",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/membership" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "sensitive_personal"],
    },
    {
      table: "store_assignment",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@bop/membership" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "approved-workforce-membership.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_membership", table: "membership" },
      principal: { kind: "module", id: "@bop/membership" },
      readPattern: "owner-repository",
      source:
        "packages/bop/membership/src/infrastructure/persistence/approved-workforce-membership-store.ts",
    },
    {
      id: "approved-workforce-membership.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_membership", table: "membership" },
      principal: { kind: "module", id: "@bop/membership" },
      readPattern: null,
      source:
        "packages/bop/membership/src/infrastructure/persistence/approved-workforce-membership-store.ts",
    },
    {
      id: "membership-brand-discovery.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_membership", table: "membership" },
      principal: { kind: "module", id: "@bop/membership" },
      readPattern: "public-query-contract",
      source: "packages/bop/membership/src/infrastructure/persistence/brand-discovery-store.ts",
    },
    {
      id: "initial-brand-membership.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_membership", table: "membership" },
      principal: { kind: "module", id: "@bop/membership" },
      readPattern: "owner-repository",
      source:
        "packages/bop/membership/src/infrastructure/persistence/initial-brand-membership-store.ts",
    },
    {
      id: "initial-brand-membership.insert",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_membership", table: "membership" },
      principal: { kind: "module", id: "@bop/membership" },
      readPattern: null,
      source:
        "packages/bop/membership/src/infrastructure/persistence/initial-brand-membership-store.ts",
    },
    {
      id: "current-membership.membership",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_membership", table: "membership" },
      principal: { kind: "module", id: "@bop/membership" },
      readPattern: "owner-repository",
      source: "packages/bop/membership/src/infrastructure/persistence/current-membership-store.ts",
    },
    {
      id: "current-membership.store_assignment",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_membership", table: "store_assignment" },
      principal: { kind: "module", id: "@bop/membership" },
      readPattern: "owner-repository",
      source: "packages/bop/membership/src/infrastructure/persistence/current-membership-store.ts",
    },
    {
      id: "store-member-scope.membership",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_membership", table: "membership" },
      principal: { kind: "module", id: "@bop/membership" },
      readPattern: "owner-repository",
      source: "packages/bop/membership/src/infrastructure/persistence/store-member-scope-source.ts",
    },
    {
      id: "store-member-scope.store_assignment",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_membership", table: "store_assignment" },
      principal: { kind: "module", id: "@bop/membership" },
      readPattern: "owner-repository",
      source: "packages/bop/membership/src/infrastructure/persistence/store-member-scope-source.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
