// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "compliance-food-safety",
    packageName: "@rms/compliance-food-safety",
    layer: "RMS",
    lifecycle: "Later",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "permission",
        packageName: "@bop/permission",
        layer: "BOP",
      },
      {
        moduleName: "tenant",
        packageName: "@bop/tenant",
        layer: "BOP",
      },
    ],
    consumedEvents: [],
    publishedEvents: [
      "rms.compliance-food-safety.compliance-finding-recorded.v1",
      "rms.compliance-food-safety.compliance-case-cancelled.v1",
      "rms.compliance-food-safety.compliance-case-closed.v1",
      "rms.compliance-food-safety.compliance-case-entered-corrective-action.v1",
      "rms.compliance-food-safety.compliance-case-escalated.v1",
      "rms.compliance-food-safety.compliance-case-opened.v1",
      "rms.compliance-food-safety.compliance-case-verification-started.v1",
      "rms.compliance-food-safety.corrective-action-assigned.v1",
      "rms.compliance-food-safety.corrective-action-completed.v1",
      "rms.compliance-food-safety.corrective-action-verification-failed.v1",
      "rms.compliance-food-safety.corrective-action-verified.v1",
      "rms.compliance-food-safety.critical-compliance-finding-detected.v1",
      "rms.compliance-food-safety.regulatory-notification-required.v1",
      "rms.compliance-food-safety.regulatory-notification-submitted.v1",
    ],
    ownedDatabase: {
      schema: null,
      tables: [],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Compliance and Food Safety Engineering Owner",
    },
  } /* module-manifest-json:end */ as const;

export const moduleManifest = defineModuleManifest(moduleManifestInput);
export default moduleManifest;
