// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "compliance-food-safety",
    packageName: "@rms/compliance-food-safety",
    layer: "RMS",
    lifecycle: "Later",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "permission",
        packageName: "@bop/permission",
        layer: "BOP",
      },
      {
        moduleName: "tenant",
        packageName: "@bop/tenant",
        layer: "BOP",
      },
    ],
    consumedEvents: [],
    publishedEvents: [],
    ownedDatabase: {
      schema: null,
      tables: [],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["none"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Compliance and Food Safety Engineering Owner",
    },
  } /* module-manifest-json:end */ as const;

export const moduleManifest = defineModuleManifest(moduleManifestInput);
export default moduleManifest;
