const id = (n: number) => `018f9916-0000-7000-8000-${n.toString(16).padStart(12, "0")}`;
export const supportCasePageFixture = {
  screenId: "PLT-SUPPORT-CASE",
  sourceAsOf: "2026-08-15T16:00:00.000Z",
  freshness: "Fresh",
  completeness: "Complete",
  environment: "Production",
  actor: "Named Platform Support operator",
  purpose: "Authorized support",
  recentMfa: true,
  cases: [
    {
      caseReference: id(1),
      caseCode: "SUP-2026-0042",
      tenant: "Pilot Tenant",
      store: "Pilot Store",
      caseType: "Diagnostic",
      purpose: "Investigate health incident",
      requesterVerified: true,
      assignedRole: "Authorized Support",
      status: "AccessGranted",
      dueAt: "2026-08-16T16:00:00.000Z",
      accessExpiresAt: "2026-08-15T16:15:00.000Z",
      actionCount: 1,
      evidenceReferences: [id(2)],
      mayAssign: false,
      mayGrant: false,
      mayRecordAction: true,
      mayRevoke: true,
      mayClose: false,
    },
  ],
  mayCreate: true,
} as const;
