const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "dining", packageName: "@rms/dining", layer: "RMS" },
  tables: [
    {
      table: "dining_host_transfer_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_exception_task",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_item_service_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_checkout_commitment",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_admission_consumption_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "dining_session_move_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_closing_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_table",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_table_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_session",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_join_capability",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["credential"],
    },
    {
      table: "dining_session_start_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "dining_join_regeneration_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "dining_participant",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_identity_admission",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "dining_session_join_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "dining_table_release_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/dining" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "host-transfer.read.dining_host_transfer_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_dining", table: "dining_host_transfer_operation" },
      principal: { kind: "module", id: "@rms/dining" },
      readPattern: "owner-repository",
      source: "packages/rms/dining/src/infrastructure/persistence/dining-host-transfer-store.ts",
    },
    {
      id: "host-transfer.write.dining_host_transfer_operation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_dining", table: "dining_host_transfer_operation" },
      principal: { kind: "module", id: "@rms/dining" },
      readPattern: null,
      source: "packages/rms/dining/src/infrastructure/persistence/dining-host-transfer-store.ts",
    },
    {
      id: "host-transfer.write.dining_session",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_dining", table: "dining_session" },
      principal: { kind: "module", id: "@rms/dining" },
      readPattern: null,
      source: "packages/rms/dining/src/infrastructure/persistence/dining-host-transfer-store.ts",
    },
    {
      id: "host-transfer.read.dining_participant",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_dining", table: "dining_participant" },
      principal: { kind: "module", id: "@rms/dining" },
      readPattern: "owner-repository",
      source: "packages/rms/dining/src/infrastructure/persistence/dining-host-transfer-store.ts",
    },
  ],
} as const;
export default databaseAccessManifestInput;
