const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "tenant", packageName: "@bop/tenant", layer: "BOP" },
  tables: [
    {
      table: "platform_brand_template_revision",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "platform_brand_template_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },

    {
      table: "brand_configuration_authoring_revision",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand_configuration_authoring_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand_store_topology_draft_revision",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand_store_topology_draft_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_reference_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@bop/tenant.store-reference.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_reference_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@bop/tenant.store-reference.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },

    {
      table: "tenant_administration_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tenant_administration_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tenant_capability_metadata_reference",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand_admin_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand_configuration_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand_store_membership_record",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "platform-brand-template-reference.platform_brand_template_revision.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "platform_brand_template_revision" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source:
        "packages/bop/tenant/src/infrastructure/persistence/platform-brand-template-reference-source.ts",
    },
    {
      id: "platform-brand-template-reference.platform_brand_template_operation.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "platform_brand_template_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source:
        "packages/bop/tenant/src/infrastructure/persistence/platform-brand-template-reference-source.ts",
    },
    {
      id: "platform-brand-template.platform_brand_template_revision.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "platform_brand_template_revision" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/platform-brand-template-store.ts",
    },
    {
      id: "platform-brand-template.platform_brand_template_revision.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "platform_brand_template_revision" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source: "packages/bop/tenant/src/infrastructure/persistence/platform-brand-template-store.ts",
    },
    {
      id: "platform-brand-template.platform_brand_template_operation.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "platform_brand_template_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/platform-brand-template-store.ts",
    },
    {
      id: "platform-brand-template.platform_brand_template_operation.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "platform_brand_template_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source: "packages/bop/tenant/src/infrastructure/persistence/platform-brand-template-store.ts",
    },

    {
      id: "brand-configuration-authoring.read.brand",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-configuration-authoring-store.ts",
    },
    {
      id: "brand-configuration-authoring.read.brand_configuration_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_configuration_version" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-configuration-authoring-store.ts",
    },
    {
      id: "brand-configuration-authoring.write.brand_configuration_version",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_configuration_version" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-configuration-authoring-store.ts",
    },
    {
      id: "brand-configuration-authoring.read.brand_configuration_authoring_revision",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_configuration_authoring_revision" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-configuration-authoring-store.ts",
    },
    {
      id: "brand-configuration-authoring.write.brand_configuration_authoring_revision",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_configuration_authoring_revision" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-configuration-authoring-store.ts",
    },
    {
      id: "brand-configuration-authoring.read.brand_configuration_authoring_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_configuration_authoring_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-configuration-authoring-store.ts",
    },
    {
      id: "brand-configuration-authoring.write.brand_configuration_authoring_operation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_configuration_authoring_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-configuration-authoring-store.ts",
    },
    {
      id: "brand-store-topology-draft.read.brand",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-store-topology-draft-store.ts",
    },
    {
      id: "brand-store-topology-draft.read.brand_store_topology_draft_revision",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_store_topology_draft_revision" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-store-topology-draft-store.ts",
    },
    {
      id: "brand-store-topology-draft.write.brand_store_topology_draft_revision",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_store_topology_draft_revision" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-store-topology-draft-store.ts",
    },
    {
      id: "brand-store-topology-draft.read.brand_store_topology_draft_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_store_topology_draft_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-store-topology-draft-store.ts",
    },
    {
      id: "brand-store-topology-draft.write.brand_store_topology_draft_operation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_store_topology_draft_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source:
        "packages/bop/tenant/src/infrastructure/persistence/brand-store-topology-draft-store.ts",
    },
    {
      id: "brand-configuration-content-source.read.brand",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/brand-lifecycle-store.ts",
    },
    {
      id: "brand-configuration-content-source.read.configuration",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_configuration_version" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/brand-lifecycle-store.ts",
    },
    {
      id: "store-reference-source.read.brand",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/store-reference-source.ts",
    },
    {
      id: "store-reference-source.read.store_reference_generation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "store_reference_generation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/store-reference-source.ts",
    },
    {
      id: "store-reference-source.read.store_reference_projection",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "store_reference_projection" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/store-reference-source.ts",
    },

    {
      id: "brand-lifecycle.read.brand",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/brand-lifecycle-store.ts",
    },
    {
      id: "brand-lifecycle.insert.brand",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source: "packages/bop/tenant/src/infrastructure/persistence/brand-lifecycle-store.ts",
    },
    {
      id: "brand-lifecycle.read.brand_admin_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_admin_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/brand-lifecycle-store.ts",
    },
    {
      id: "brand-lifecycle.insert.brand_admin_operation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_admin_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source: "packages/bop/tenant/src/infrastructure/persistence/brand-lifecycle-store.ts",
    },

    {
      id: "merchant-organization.brand",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/merchant-organization-source.ts",
    },
    {
      id: "merchant-organization.store",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "store" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/merchant-organization-source.ts",
    },
    {
      id: "receipt-store-identity-source.read.store",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "store" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/receipt-store-identity-source.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
