const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "tenant", packageName: "@bop/tenant", layer: "BOP" },
  tables: [
    {
      table: "tenant_administration_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tenant_administration_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tenant_capability_metadata_reference",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand_admin_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand_configuration_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand_store_membership_record",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "brand",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/tenant" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "brand-lifecycle.read.brand",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/brand-lifecycle-store.ts",
    },
    {
      id: "brand-lifecycle.insert.brand",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source: "packages/bop/tenant/src/infrastructure/persistence/brand-lifecycle-store.ts",
    },
    {
      id: "brand-lifecycle.read.brand_admin_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_admin_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/brand-lifecycle-store.ts",
    },
    {
      id: "brand-lifecycle.insert.brand_admin_operation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand_admin_operation" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: null,
      source: "packages/bop/tenant/src/infrastructure/persistence/brand-lifecycle-store.ts",
    },

    {
      id: "merchant-organization.brand",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "brand" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/merchant-organization-source.ts",
    },
    {
      id: "merchant-organization.store",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "store" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/merchant-organization-source.ts",
    },
    {
      id: "receipt-store-identity-source.read.store",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_tenant", table: "store" },
      principal: { kind: "module", id: "@bop/tenant" },
      readPattern: "owner-repository",
      source: "packages/bop/tenant/src/infrastructure/persistence/receipt-store-identity-source.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
