const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "kitchen", packageName: "@rms/kitchen", layer: "RMS" },
  tables: [
    {
      table: "kitchen_allergen_acknowledgement",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/kitchen" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "kitchen_allergen_incident_link",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/kitchen" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "kitchen_allergen_review",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/kitchen" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "kitchen_action_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/kitchen" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "kitchen_order_item_ready_result",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/kitchen" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal"],
    },
    {
      table: "kitchen_ready_publication",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/kitchen" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "kitchen_ticket",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/kitchen" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "kitchen_work_item",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/kitchen" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "kitchen_work_lifecycle_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/kitchen" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "personal"],
    },
    {
      table: "kitchen_work_queue_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/kitchen.queue.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "kitchen_work_queue_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/kitchen.queue.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
export default databaseAccessManifest;
