// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "pricing",
    packageName: "@rms/pricing",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "effective-period",
        packageName: "@bop/effective-period",
        layer: "BOP",
      },
      {
        moduleName: "permission",
        packageName: "@bop/permission",
        layer: "BOP",
      },
      {
        moduleName: "tenant",
        packageName: "@bop/tenant",
        layer: "BOP",
      },
    ],
    consumedEvents: [],
    publishedEvents: [
      "rms.pricing.price-book-archived.v1",
      "rms.pricing.price-book-draft-created.v1",
      "rms.pricing.price-book-draft-replaced.v1",
      "rms.pricing.price-book-version-published.v1",
    ],
    ownedDatabase: {
      schema: "rms_pricing",
      tables: [
        "tax_configuration",
        "tax_configuration_version",
        "tax_configuration_rule",
        "tax_configuration_operation_record",
        "price_book",
        "price_book_version",
        "price_entry",
        "price_book_operation_record",
        "price_book_admin_projection_generation",
        "price_book_admin_projection",
        "price_book_entry_projection",
        "price_book_admin_projection_checkpoint",
        "price_quote",
        "price_quote_line",
        "price_quote_tax_line",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["none"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Pricing Engineering Owner",
    },
  } as const;

/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
