const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "ordering", packageName: "@rms/ordering", layer: "RMS" },
  tables: [
    {
      table: "order_batch_checkout_cancellation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_batch_checkout_expiry",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_closure_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_cancellation_request_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_cart_replacement",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "additional_dining_batch_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal"],
    },
    {
      table: "order_revision",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "digital_receipt_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal"],
    },
    {
      table: "order_fulfillment_completion_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },

    {
      table: "order_termination_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_acceptance_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_payment_disposition_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },

    {
      table: "order_payment_acceptance_wait",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },

    {
      table: "order_payment_failure_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "checkout_session_allocation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "checkout_session_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_checkout_details_link",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "checkout_details_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal"],
    },
    {
      table: "order_capacity_link",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "dining_cart_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "cart_quote_expiry_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "cart_binding_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "cart",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "cart_line",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "cart_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "ephemeral-technical",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "cart_quote_attachment",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "cart_quote_attachment_line",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "cart_lifecycle_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "ephemeral-technical",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "order_number_counter",
      classification: "technical-control-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_number_allocation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_header",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_submission_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_batch",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_item",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "order_amendment",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_amendment_change",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "order_amendment_state_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_amendment_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "ephemeral-technical",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_status_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/ordering.order-status.v1" },
      allowedReadPatterns: ["public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_status_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/ordering.order-status.v1" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "batch-checkout-cancellation.read.order_batch_checkout_cancellation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch_checkout_cancellation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-batch-checkout-expiry-store.ts",
    },
    {
      id: "batch-checkout-cancellation.write.order_batch_checkout_cancellation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch_checkout_cancellation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-batch-checkout-expiry-store.ts",
    },
    {
      id: "batch-checkout-cancellation.write.order_revision",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-batch-checkout-expiry-store.ts",
    },
    {
      id: "batch-cancellation.read.order-termination-store",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch_checkout_cancellation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-termination-store.ts",
    },
    {
      id: "batch-cancellation.read.dining-order-item-state-reader",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch_checkout_cancellation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/dining-order-item-state-reader.ts",
    },
    {
      id: "batch-checkout-expiry.read.order_batch",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-batch-checkout-expiry-store.ts",
    },
    {
      id: "batch-checkout-expiry.read.order_capacity_link",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_capacity_link" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-batch-checkout-expiry-store.ts",
    },
    {
      id: "batch-checkout-expiry.read.checkout_session_allocation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "checkout_session_allocation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-batch-checkout-expiry-store.ts",
    },

    {
      id: "batch-checkout-expiry.read.order_batch_checkout_expiry",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch_checkout_expiry" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-batch-checkout-expiry-store.ts",
    },
    {
      id: "batch-checkout-expiry.write.order_batch_checkout_expiry",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch_checkout_expiry" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-batch-checkout-expiry-store.ts",
    },
    {
      id: "batch-checkout-expiry.read.order_header",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_header" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-batch-checkout-expiry-store.ts",
    },

    {
      id: "order-refund-basis.read.order_batch",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch" },
      principal: { kind: "module", id: "@rms/ordering" },
      source: "packages/rms/ordering/src/infrastructure/persistence/order-refund-basis-reader.ts",
    },
    {
      id: "order-refund-basis.read.order_submission_record",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_submission_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      source: "packages/rms/ordering/src/infrastructure/persistence/order-refund-basis-reader.ts",
    },
    {
      id: "order-refund-basis.read.order_item",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_item" },
      principal: { kind: "module", id: "@rms/ordering" },
      source: "packages/rms/ordering/src/infrastructure/persistence/order-refund-basis-reader.ts",
    },
    {
      id: "digital-receipt-store.read.digital_receipt_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "digital_receipt_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/digital-receipt-store.ts",
    },
    {
      id: "digital-receipt-store.write.digital_receipt_record",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "digital_receipt_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/digital-receipt-store.ts",
    },
    {
      id: "digital-receipt-store.read.order_header",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_header" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/digital-receipt-store.ts",
    },
    {
      id: "digital-receipt-store.read.order_submission_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_submission_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/digital-receipt-store.ts",
    },
    {
      id: "order-payment-disposition.read.order_batch",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-payment-disposition-store.ts",
    },

    {
      id: "order-payment-disposition.write.order_payment_disposition_record",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_payment_disposition_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-payment-disposition-store.ts",
    },

    {
      id: "order-payment-acceptance-wait.write.order_payment_acceptance_wait",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_payment_acceptance_wait" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-payment-acceptance-wait-store.ts",
    },

    {
      id: "order-payment-disposition.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_payment_disposition_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-payment-disposition-store.ts",
    },

    {
      id: "order-payment-acceptance-wait.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_payment_acceptance_wait" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-payment-acceptance-wait-store.ts",
    },
    {
      id: "order-payment-failure.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_payment_failure_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-payment-failure-store.ts",
    },
    {
      id: "order-payment-failure.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_payment_failure_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-payment-failure-store.ts",
    },

    {
      id: "checkout-session-store.read.checkout_session_allocation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "checkout_session_allocation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/checkout-session-store.ts",
    },
    {
      id: "checkout-session-allocation-store.read.checkout_session_allocation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "checkout_session_allocation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/checkout-session-allocation-store.ts",
    },
    {
      id: "checkout-session-allocation-store.write.checkout_session_allocation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "checkout_session_allocation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/checkout-session-allocation-store.ts",
    },
    {
      id: "checkout-session-allocation-store.read.cart",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/checkout-session-allocation-store.ts",
    },
    {
      id: "checkout-session-store.read.checkout_session_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "checkout_session_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/checkout-session-store.ts",
    },
    {
      id: "checkout-session-store.write.checkout_session_record",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "checkout_session_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/checkout-session-store.ts",
    },
    {
      id: "checkout-session-store.read.cart",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/checkout-session-store.ts",
    },
    {
      id: "checkout-session-store.read.cart_quote_attachment",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_quote_attachment" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/checkout-session-store.ts",
    },
    {
      id: "order-creation-store.read.cart",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.read.cart_line",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_line" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.read.order_number_counter",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_number_counter" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.read.order_number_allocation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_number_allocation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.read.order_header",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_header" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.read.order_submission_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_submission_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.read.order_batch",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.read.order_item",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_item" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.write.order_number_counter",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_number_counter" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.write.order_number_allocation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_number_allocation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.write.cart",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.write.cart_line",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_line" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-submitted-history-source.read.order_revision",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-submitted-history-source.ts",
    },
    {
      id: "order-submitted-history-source.read.order_acceptance_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_acceptance_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-submitted-history-source.ts",
    },
    {
      id: "order-submitted-history-source.read.additional_dining_batch_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "additional_dining_batch_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-submitted-history-source.ts",
    },
    {
      id: "additional-dining-batch-store.read.order_capacity_link",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_capacity_link" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.read.order_submission_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_submission_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.read.checkout_details_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "checkout_details_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.write.order_checkout_details_link",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_checkout_details_link" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.read.checkout_session_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "checkout_session_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.write.order_capacity_link",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_capacity_link" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.read.cart",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.write.cart",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.read.cart_line",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_line" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.write.cart_line",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_line" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.read.additional_dining_batch_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "additional_dining_batch_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.write.additional_dining_batch_record",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "additional_dining_batch_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.read.order_header",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_header" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.read.order_revision",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.write.order_revision",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.read.order_batch",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.write.order_batch",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.write.order_item",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_item" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "additional-dining-batch-store.write.order_submission_record",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_submission_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/additional-dining-batch-store.ts",
    },
    {
      id: "order-termination-store.read.additional_dining_batch_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "additional_dining_batch_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-termination-store.ts",
    },
    {
      id: "order-termination-store.read.order_revision",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-termination-store.ts",
    },
    {
      id: "order-termination-store.write.order_revision",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-termination-store.ts",
    },
    {
      id: "order-fulfillment-completion-store.read.order_revision",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-fulfillment-completion-store.ts",
    },
    {
      id: "order-fulfillment-completion-store.write.order_revision",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source:
        "packages/rms/ordering/src/infrastructure/persistence/order-fulfillment-completion-store.ts",
    },
    {
      id: "order-acceptance-store.read.order_revision",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-acceptance-store.ts",
    },
    {
      id: "order-acceptance-store.write.order_revision",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-acceptance-store.ts",
    },
    {
      id: "order-creation-store.write.order_revision",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_revision" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.write.order_header",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_header" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.write.order_submission_record",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_submission_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.write.order_batch",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "order-creation-store.write.order_item",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_item" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-store.ts",
    },
    {
      id: "receipt-order-source.read.order_header",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_header" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/receipt-order-source.ts",
    },
    {
      id: "receipt-order-source.read.order_submission_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_submission_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/receipt-order-source.ts",
    },
    {
      id: "receipt-order-source.read.order_batch",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/receipt-order-source.ts",
    },
    {
      id: "receipt-order-source.read.order_item",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_item" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/receipt-order-source.ts",
    },
    {
      id: "order-creation-query.read.order_submission_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_submission_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-query-store.ts",
    },
    {
      id: "order-creation-query.read.order_header",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_header" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-query-store.ts",
    },
    {
      id: "order-creation-query.read.order_batch",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-query-store.ts",
    },
    {
      id: "order-creation-query.read.order_item",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_item" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-query-store.ts",
    },
    {
      id: "order-creation-query.read.order_number_allocation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_number_allocation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/order-creation-query-store.ts",
    },
    {
      id: "merchant-item-labels.read.order_item",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_item" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/merchant-order-item-labels.ts",
    },
    {
      id: "merchant-item-labels.read.order_batch",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_batch" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/merchant-order-item-labels.ts",
    },
    {
      id: "merchant-item-labels.read.order_submission_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "order_submission_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/merchant-order-item-labels.ts",
    },
    {
      id: "merchant-item-labels.read.additional_dining_batch_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "additional_dining_batch_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/merchant-order-item-labels.ts",
    },
  ],
} as const;

export default databaseAccessManifestInput;
