const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "ordering", packageName: "@rms/ordering", layer: "RMS" },
  tables: [
    {
      table: "cart_customer_owner",
      classification: "technical-control-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "cart_creation_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "ephemeral-technical",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },

    {
      table: "cart",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "cart_line",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "cart_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "ephemeral-technical",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "cart_quote_attachment",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "cart_quote_attachment_line",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "cart_lifecycle_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "ephemeral-technical",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "order_number_counter",
      classification: "technical-control-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_number_allocation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_header",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_submission_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_batch",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_item",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "order_amendment",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_amendment_change",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal", "health"],
    },
    {
      table: "order_amendment_state_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_amendment_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/ordering" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "ephemeral-technical",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_status_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/ordering.order-status.v1" },
      allowedReadPatterns: ["public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "order_status_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/ordering.order-status.v1" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "cart-item.cart.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/cart-item-store.ts",
    },
    {
      id: "cart-item.cart.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/cart-item-store.ts",
    },
    {
      id: "cart-item.cart_line.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_line" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/cart-item-store.ts",
    },
    {
      id: "cart-item.cart_line.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_line" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/cart-item-store.ts",
    },
    {
      id: "cart-item.cart_operation_record.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_operation_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/cart-item-store.ts",
    },
    {
      id: "cart-item.cart_operation_record.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_operation_record" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/cart-item-store.ts",
    },
    {
      id: "customer-cart.cart.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/customer-cart-store.ts",
    },
    {
      id: "customer-cart.cart.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/customer-cart-store.ts",
    },
    {
      id: "customer-cart.cart_line.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_line" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/customer-cart-store.ts",
    },
    {
      id: "customer-cart.cart_customer_owner.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_customer_owner" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/customer-cart-store.ts",
    },
    {
      id: "customer-cart.cart_customer_owner.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_customer_owner" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/customer-cart-store.ts",
    },
    {
      id: "customer-cart.cart_creation_operation.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_creation_operation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: "owner-repository",
      source: "packages/rms/ordering/src/infrastructure/persistence/customer-cart-store.ts",
    },
    {
      id: "customer-cart.cart_creation_operation.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_ordering", table: "cart_creation_operation" },
      principal: { kind: "module", id: "@rms/ordering" },
      readPattern: null,
      source: "packages/rms/ordering/src/infrastructure/persistence/customer-cart-store.ts",
    },
  ],
} as const;

export default databaseAccessManifestInput;
