const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "publishing", packageName: "@bop/publishing", layer: "BOP" },
  tables: [
    {
      table: "platform_template_publishing_head",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/publishing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "platform_template_publishing_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/publishing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option_price_review_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/publishing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option_set_publication_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/publishing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "publishing_mutation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/publishing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "live_gate_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@bop/publishing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "live_gate_requirement",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@bop/publishing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "live_gate_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/publishing" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "brand-template-reference.read.platform_template_publishing_head",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "platform_template_publishing_head" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source:
        "packages/bop/publishing/src/infrastructure/persistence/platform-template-brand-reference-source.ts",
    },
    {
      id: "brand-template-reference.read.platform_template_publishing_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "platform_template_publishing_operation" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source:
        "packages/bop/publishing/src/infrastructure/persistence/platform-template-brand-reference-source.ts",
    },
    {
      id: "platform-template-publishing.read.platform_template_publishing_head",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "platform_template_publishing_head" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source: "packages/bop/publishing/src/infrastructure/persistence/platform-publishing-store.ts",
    },
    {
      id: "platform-template-publishing.write.platform_template_publishing_head",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "platform_template_publishing_head" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: null,
      source: "packages/bop/publishing/src/infrastructure/persistence/platform-publishing-store.ts",
    },
    {
      id: "platform-template-publishing.read.platform_template_publishing_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "platform_template_publishing_operation" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source: "packages/bop/publishing/src/infrastructure/persistence/platform-publishing-store.ts",
    },
    {
      id: "platform-template-publishing.write.platform_template_publishing_operation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "platform_template_publishing_operation" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: null,
      source: "packages/bop/publishing/src/infrastructure/persistence/platform-publishing-store.ts",
    },
    {
      id: "option-price-review-operation.read.option_price_review_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "option_price_review_operation" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source:
        "packages/bop/publishing/src/infrastructure/persistence/option-price-review-operation-store.ts",
    },
    {
      id: "option-price-review-operation.write.option_price_review_operation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "option_price_review_operation" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: null,
      source:
        "packages/bop/publishing/src/infrastructure/persistence/option-price-review-operation-store.ts",
    },
    {
      id: "option-price-review-operation.read.publishing_mutation_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "publishing_mutation_record" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source:
        "packages/bop/publishing/src/infrastructure/persistence/option-price-review-operation-store.ts",
    },
    {
      id: "option-publication-history.read.publishing_mutation_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "publishing_mutation_record" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source:
        "packages/bop/publishing/src/infrastructure/persistence/option-set-publication-history-store.ts",
    },
    {
      id: "option-publication-operation.read.option_set_publication_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "option_set_publication_operation" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source:
        "packages/bop/publishing/src/infrastructure/persistence/option-set-publication-operation-store.ts",
    },
    {
      id: "option-publication-operation.write.option_set_publication_operation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "option_set_publication_operation" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: null,
      source:
        "packages/bop/publishing/src/infrastructure/persistence/option-set-publication-operation-store.ts",
    },
    {
      id: "option-publication-operation.read.publishing_mutation_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "publishing_mutation_record" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source:
        "packages/bop/publishing/src/infrastructure/persistence/option-set-publication-operation-store.ts",
    },
    {
      id: "current-live-gate.read.live_gate_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "live_gate_version" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source: "packages/bop/publishing/src/infrastructure/persistence/current-live-gate-source.ts",
    },
    {
      id: "current-live-gate.read.live_gate_requirement",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_publishing", table: "live_gate_requirement" },
      principal: { kind: "module", id: "@bop/publishing" },
      readPattern: "owner-repository",
      source: "packages/bop/publishing/src/infrastructure/persistence/current-live-gate-source.ts",
    },
  ],
} as const;
export const databaseAccessManifest = databaseAccessManifestInput;
export default databaseAccessManifest;
