// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "printing-device",
    packageName: "@rms/printing-device",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "permission",
        packageName: "@bop/permission",
        layer: "BOP",
      },
      {
        moduleName: "tenant",
        packageName: "@bop/tenant",
        layer: "BOP",
      },
    ],
    consumedEvents: [],
    publishedEvents: [
      "rms.printing-device.device-activated.v1",
      "rms.printing-device.device-capability-changed.v1",
      "rms.printing-device.device-credential-revoked.v1",
      "rms.printing-device.device-health-changed.v1",
      "rms.printing-device.device-provisioned.v1",
      "rms.printing-device.device-retired.v1",
      "rms.printing-device.device-suspended.v1",
    ],
    ownedDatabase: {
      schema: "rms_device",
      tables: [
        "device",
        "device_assignment",
        "device_capability_version",
        "device_health_current",
        "device_health_signal",
        "device_operation",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier", "credential"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Printing and Device Integration Engineering Owner",
    },
  } /* module-manifest-json:end */ as const;

export const moduleManifest = defineModuleManifest(moduleManifestInput);
export default moduleManifest;
