const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "pricing", packageName: "@rms/pricing", layer: "RMS" },
  tables: [
    {
      table: "tax_configuration",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tax_configuration_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tax_configuration_rule",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tax_configuration_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tax_config_admin_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.tax-config-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tax_config_admin_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.tax-config-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tax_config_rule_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.tax-config-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tax_config_receipt_fixture_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.tax-config-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "tax_config_admin_projection_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.tax-config-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_book",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "promotion",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "promotion_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "promotion_eligibility_reference",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "promotion_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "promotion_admin_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.promotion-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "promotion_admin_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.promotion-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "promotion_admin_projection_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.promotion-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_book_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_entry",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_book_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_book_admin_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.price-book-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_book_admin_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.price-book-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_book_entry_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.price-book-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_book_admin_projection_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/pricing.price-book-admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_quote_request",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_quote",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_quote_line",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "price_quote_tax_line",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/pricing" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
