// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "dining",
    packageName: "@rms/dining",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "permission",
        packageName: "@bop/permission",
        layer: "BOP",
      },
      {
        moduleName: "public-capability",
        packageName: "@bop/public-capability",
        layer: "BOP",
      },
      {
        moduleName: "task",
        packageName: "@bop/task",
        layer: "BOP",
      },
      {
        moduleName: "tenant",
        packageName: "@bop/tenant",
        layer: "BOP",
      },
    ],
    consumedEvents: [],
    publishedEvents: [],
    ownedDatabase: {
      schema: "rms_dining",
      tables: [
        "dining_table",
        "dining_table_operation",
        "dining_session",
        "dining_join_capability",
        "dining_session_start_operation",
        "dining_join_regeneration_operation",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier", "credential"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Dining Engineering Owner",
    },
  } as const;

/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
