// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import {
  defineModuleManifest,
  type ModuleManifest,
} from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput: ModuleManifest =
  /* module-manifest-json:begin */
  {
    moduleName: "inventory",
    packageName: "@rms/inventory",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
    ],
    consumedEvents: [],
    publishedEvents: [],
    ownedDatabase: {
      schema: "rms_inventory",
      tables: [
        "item_sku_mapping_version",
        "configuration_reference_generation",
        "recipe_configuration_source_version",
        "recipe_configuration_source_capture",
        "inventory_item",
        "inventory_item_version",
        "inventory_item_operation",
        "stock_account",
        "stock_balance",
        "stock_movement",
        "stock_reservation_version",
        "stock_lot_hold_version",
        "stock_reservation_set",
        "submission_final_validation",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Inventory Engineering Owner",
    },
  };

/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
