// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "fulfillment",
    packageName: "@rms/fulfillment",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "eventing",
        packageName: "@bop/eventing",
        layer: "BOP",
      },
      {
        moduleName: "public-capability",
        packageName: "@bop/public-capability",
        layer: "BOP",
      },
      {
        moduleName: "kitchen",
        packageName: "@rms/kitchen",
        layer: "RMS",
      },
      {
        moduleName: "ordering",
        packageName: "@rms/ordering",
        layer: "RMS",
      },
    ],
    consumedEvents: ["rms.kitchen.kitchen-item-ready.v1", "rms.ordering.order-confirmed.v1"],
    publishedEvents: [],
    ownedDatabase: {
      schema: "rms_fulfillment",
      tables: [
        "fulfillment",
        "fulfillment_creation_operation",
        "fulfillment_item",
        "fulfillment_item_ready_result",
        "pickup_proof_generation",
        "pickup_proof_invalidation",
        "pickup_proof_operation",
        "pickup_proof_verification",
        "fulfillment_ready_operation",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier", "credential"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Fulfillment Engineering Owner",
    },
  } as const;

/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
