// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "catalog",
    packageName: "@rms/catalog",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "effective-period",
        packageName: "@bop/effective-period",
        layer: "BOP",
      },
      {
        moduleName: "eventing",
        packageName: "@bop/eventing",
        layer: "BOP",
      },
      {
        moduleName: "permission",
        packageName: "@bop/permission",
        layer: "BOP",
      },
      {
        moduleName: "publishing",
        packageName: "@bop/publishing",
        layer: "BOP",
      },
      {
        moduleName: "tenant",
        packageName: "@bop/tenant",
        layer: "BOP",
      },
    ],
    consumedEvents: ["rms.catalog.menu-published.v1"],
    publishedEvents: [
      "rms.catalog.bundle-draft-created.v1",
      "rms.catalog.bundle-draft-replaced.v1",
      "rms.catalog.bundle-lifecycle-changed.v1",
      "rms.catalog.bundle-version-published.v1",
      "rms.catalog.menu-published.v1",
    ],
    ownedDatabase: {
      schema: "rms_catalog",
      tables: [
        "product",
        "product_version",
        "sku",
        "product_operation_record",
        "category",
        "category_operation_record",
        "menu",
        "menu_version",
        "menu_version_store",
        "menu_version_channel",
        "menu_version_order_type",
        "menu_section",
        "menu_section_category",
        "sellable_placement",
        "menu_operation_record",
        "option_set",
        "option_set_version",
        "option",
        "option_conflict",
        "product_option_binding",
        "product_option_binding_option",
        "product_option_binding_sku_scope",
        "product_option_binding_channel",
        "option_set_operation_record",
        "availability_rule",
        "availability_rule_operation_record",
        "menu_publication_revision",
        "menu_publication_release",
        "menu_release_effective_period",
        "menu_publication_operation_record",
        "published_menu_projection_generation",
        "published_menu_projection",
        "published_menu_projection_section",
        "published_menu_projection_sellable",
        "published_menu_projection_checkpoint",
        "allergen_registry_version",
        "allergen_registry_entry",
        "allergen_source_evidence",
        "allergen_source_assertion",
        "menu_allergen_validation_evidence",
        "menu_sellable_allergen_disclosure",
        "bundle",
        "bundle_version",
        "bundle_component_group",
        "bundle_component_sellable",
        "bundle_availability_rule",
        "bundle_operation_record",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["none"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Catalog Engineering Owner",
    },
  } as const;

/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
