const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "catalog", packageName: "@rms/catalog", layer: "RMS" },
  tables: [
    {
      table: "product",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "sku",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "category",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "category_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version_store",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version_channel",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version_order_type",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_section",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_section_category",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "sellable_placement",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option_set",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option_set_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option_conflict",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_option_binding",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_option_binding_option",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_option_binding_sku_scope",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_option_binding_channel",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option_set_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "availability_rule",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "availability_rule_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "availability_workbench_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.availability-workbench.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "availability_workbench_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.availability-workbench.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "availability_workbench_projection_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.availability-workbench.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_publication_revision",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_publication_release",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_release_effective_period",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_publication_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "published_menu_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "published_menu_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "published_menu_projection_section",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "published_menu_projection_sellable",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "published_menu_projection_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "allergen_registry_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "allergen_registry_entry",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "allergen_source_evidence",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "allergen_source_assertion",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_allergen_validation_evidence",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_sellable_allergen_disclosure",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.allergen-validation.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle_component_group",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle_component_sellable",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle_availability_rule",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
