const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "catalog", packageName: "@rms/catalog", layer: "RMS" },
  tables: [
    {
      table: "product",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "sku",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "category",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "category_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version_store",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version_channel",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version_order_type",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_section",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_section_category",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "sellable_placement",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
