const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "catalog", packageName: "@rms/catalog", layer: "RMS" },
  tables: [
    {
      table: "product",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "sku",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_operation_snapshot",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "category",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "category_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version_store",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version_channel",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_version_order_type",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_section",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_section_category",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "sellable_placement",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option_set",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option_set_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option_conflict",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_option_binding",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_option_binding_option",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_option_binding_sku_scope",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "product_option_binding_channel",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "option_set_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "availability_rule",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "availability_rule_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "availability_workbench_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.availability-workbench.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "availability_workbench_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.availability-workbench.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "availability_workbench_projection_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.availability-workbench.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_publication_revision",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_publication_release",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_release_effective_period",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_review_content",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_publication_operation_snapshot",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_publication_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "published_menu_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "published_menu_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "published_menu_projection_section",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "published_menu_projection_sellable",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "published_menu_projection_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "allergen_registry_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "allergen_registry_entry",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "allergen_source_evidence",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "allergen_source_assertion",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_allergen_validation_evidence",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "menu_sellable_allergen_disclosure",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/catalog.allergen-validation.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle_component_group",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle_component_sellable",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle_availability_rule",
      classification: "relationship-assignment",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "bundle_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/catalog" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "current-menu-placement.read.menu",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "menu" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-placement-store.ts",
    },
    {
      id: "current-menu-placement.read.menu_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "menu_version" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-placement-store.ts",
    },
    {
      id: "current-menu-placement.read.menu_section",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "menu_section" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-placement-store.ts",
    },
    {
      id: "current-menu-placement.read.sellable_placement",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "sellable_placement" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-placement-store.ts",
    },
    {
      id: "current-menu-placement.read.sku",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "sku" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-placement-store.ts",
    },

    {
      id: "current-option-bindings.read.sku",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "sku" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source:
        "packages/rms/catalog/src/infrastructure/persistence/current-option-bindings-store.ts",
    },
    {
      id: "current-option-bindings.read.product_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "product_version" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source:
        "packages/rms/catalog/src/infrastructure/persistence/current-option-bindings-store.ts",
    },
    {
      id: "current-option-bindings.read.option_set",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "option_set" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source:
        "packages/rms/catalog/src/infrastructure/persistence/current-option-bindings-store.ts",
    },
    {
      id: "current-option-bindings.read.option_set_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "option_set_version" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source:
        "packages/rms/catalog/src/infrastructure/persistence/current-option-bindings-store.ts",
    },
    {
      id: "current-option-bindings.read.option",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "option" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source:
        "packages/rms/catalog/src/infrastructure/persistence/current-option-bindings-store.ts",
    },
    {
      id: "current-option-bindings.read.option_conflict",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "option_conflict" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source:
        "packages/rms/catalog/src/infrastructure/persistence/current-option-bindings-store.ts",
    },
    {
      id: "current-option-bindings.read.product_option_binding",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "product_option_binding" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source:
        "packages/rms/catalog/src/infrastructure/persistence/current-option-bindings-store.ts",
    },
    {
      id: "current-option-bindings.read.product_option_binding_option",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "product_option_binding_option" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source:
        "packages/rms/catalog/src/infrastructure/persistence/current-option-bindings-store.ts",
    },
    {
      id: "current-option-bindings.read.product_option_binding_sku_scope",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "product_option_binding_sku_scope" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source:
        "packages/rms/catalog/src/infrastructure/persistence/current-option-bindings-store.ts",
    },
    {
      id: "current-option-bindings.read.product_option_binding_channel",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "product_option_binding_channel" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source:
        "packages/rms/catalog/src/infrastructure/persistence/current-option-bindings-store.ts",
    },

    {
      id: "current-sku.read.product",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "product" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-sku-store.ts",
    },
    {
      id: "current-sku.read.product_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "product_version" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-sku-store.ts",
    },
    {
      id: "current-sku.read.sku",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "sku" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-sku-store.ts",
    },

    {
      id: "current-menu-release.read.menu_publication_revision",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "menu_publication_revision" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-release-store.ts",
    },
    {
      id: "current-menu-release.read.menu_publication_release",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "menu_publication_release" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-release-store.ts",
    },
    {
      id: "current-menu-release.read.menu_release_effective_period",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "menu_release_effective_period" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-release-store.ts",
    },
    {
      id: "current-menu-release.read.menu_version_store",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "menu_version_store" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-release-store.ts",
    },
    {
      id: "current-menu-release.read.menu_version_channel",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "menu_version_channel" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-release-store.ts",
    },
    {
      id: "current-menu-release.read.menu_version_order_type",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "menu_version_order_type" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/current-menu-release-store.ts",
    },

    {
      id: "availability.read.availability_rule",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "availability_rule" },
      principal: { kind: "module", id: "@rms/catalog" },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/availability-query-store.ts",
    },
    {
      id: "published-menu.write.published_menu_projection_generation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "published_menu_projection_generation" },
      principal: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      readPattern: null,
      source: "packages/rms/catalog/src/infrastructure/persistence/published-menu-query-store.ts",
    },
    {
      id: "published-menu.write.published_menu_projection",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "published_menu_projection" },
      principal: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      readPattern: null,
      source: "packages/rms/catalog/src/infrastructure/persistence/published-menu-query-store.ts",
    },
    {
      id: "published-menu.write.published_menu_projection_section",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "published_menu_projection_section" },
      principal: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      readPattern: null,
      source: "packages/rms/catalog/src/infrastructure/persistence/published-menu-query-store.ts",
    },
    {
      id: "published-menu.write.published_menu_projection_sellable",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "published_menu_projection_sellable" },
      principal: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      readPattern: null,
      source: "packages/rms/catalog/src/infrastructure/persistence/published-menu-query-store.ts",
    },
    {
      id: "published-menu.write.published_menu_projection_checkpoint",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_catalog", table: "published_menu_projection_checkpoint" },
      principal: { kind: "projection-builder", id: "@rms/catalog.published-menu.v1" },
      readPattern: null,
      source: "packages/rms/catalog/src/infrastructure/persistence/published-menu-query-store.ts",
    },
    {
      id: "published-menu.read.published_menu_projection_generation",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "rms_catalog",
        table: "published_menu_projection_generation",
      },
      principal: {
        kind: "module",
        id: "@rms/catalog",
      },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/published-menu-query-store.ts",
    },
    {
      id: "published-menu.read.published_menu_projection",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "rms_catalog",
        table: "published_menu_projection",
      },
      principal: {
        kind: "module",
        id: "@rms/catalog",
      },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/published-menu-query-store.ts",
    },
    {
      id: "published-menu.read.published_menu_projection_section",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "rms_catalog",
        table: "published_menu_projection_section",
      },
      principal: {
        kind: "module",
        id: "@rms/catalog",
      },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/published-menu-query-store.ts",
    },
    {
      id: "published-menu.read.published_menu_projection_sellable",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "rms_catalog",
        table: "published_menu_projection_sellable",
      },
      principal: {
        kind: "module",
        id: "@rms/catalog",
      },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/published-menu-query-store.ts",
    },
    {
      id: "published-menu.read.published_menu_projection_checkpoint",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "rms_catalog",
        table: "published_menu_projection_checkpoint",
      },
      principal: {
        kind: "module",
        id: "@rms/catalog",
      },
      readPattern: "owner-repository",
      source: "packages/rms/catalog/src/infrastructure/persistence/published-menu-query-store.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
