const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "fulfillment", packageName: "@rms/fulfillment", layer: "RMS" },
  tables: [
    {
      table: "fulfillment_completion_publication",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "pickup_handoff_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal"],
    },
    {
      table: "pickup_handoff_item",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "pickup_in_person_verification",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "pickup_handoff_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier", "personal"],
    },
    {
      table: "capacity_asap_commitment",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "capacity_hold_terminal",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "capacity_allocation",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "capacity_allocation_terminal",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "capacity_slot",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "capacity_slot_configuration",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "capacity_hold",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "fulfillment",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "fulfillment_creation_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "fulfillment_item",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "fulfillment_item_ready_result",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "fulfillment_ready_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "pickup_proof_generation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "pickup_proof_invalidation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "pickup_proof_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "pickup_proof_verification",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/fulfillment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "current-pickup-capacity.read.capacity_slot",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_slot" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/current-pickup-capacity-store.ts",
    },
    {
      id: "current-pickup-capacity.read.capacity_slot_configuration",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_slot_configuration" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/current-pickup-capacity-store.ts",
    },
    {
      id: "current-pickup-capacity.read.capacity_hold",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_hold" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/current-pickup-capacity-store.ts",
    },
    {
      id: "current-pickup-capacity.read.capacity_hold_terminal",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_hold_terminal" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/current-pickup-capacity-store.ts",
    },
    {
      id: "current-pickup-capacity.read.capacity_allocation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_allocation" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/current-pickup-capacity-store.ts",
    },
    {
      id: "current-pickup-capacity.read.capacity_allocation_terminal",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_allocation_terminal" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/current-pickup-capacity-store.ts",
    },
    {
      id: "current-pickup-capacity.read.capacity_asap_commitment",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_asap_commitment" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/current-pickup-capacity-store.ts",
    },

    {
      id: "asap-capacity.read.capacity_asap_commitment",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_asap_commitment" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source: "packages/rms/fulfillment/src/infrastructure/persistence/asap-capacity-store.ts",
    },
    {
      id: "asap-capacity.write.capacity_asap_commitment",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_asap_commitment" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: null,
      source: "packages/rms/fulfillment/src/infrastructure/persistence/asap-capacity-store.ts",
    },
    {
      id: "asap-capacity.read.capacity_slot",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_slot" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source: "packages/rms/fulfillment/src/infrastructure/persistence/asap-capacity-store.ts",
    },

    {
      id: "capacity-allocation-terminal.read.capacity_slot",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_slot" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-allocation-terminal-store.ts",
    },
    {
      id: "capacity-allocation-terminal.read.capacity_hold",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_hold" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-allocation-terminal-store.ts",
    },
    {
      id: "capacity-allocation-terminal.read.capacity_allocation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_allocation" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-allocation-terminal-store.ts",
    },
    {
      id: "capacity-allocation-terminal.read.capacity_allocation_terminal",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_allocation_terminal" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-allocation-terminal-store.ts",
    },
    {
      id: "capacity-allocation-terminal.write.capacity_allocation_terminal",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_allocation_terminal" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: null,
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-allocation-terminal-store.ts",
    },
    {
      id: "capacity-transition.read.capacity_slot",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_slot" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-hold-transition-store.ts",
    },
    {
      id: "capacity-transition.read.capacity_hold",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_hold" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-hold-transition-store.ts",
    },
    {
      id: "capacity-transition.read.capacity_hold_terminal",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_hold_terminal" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-hold-transition-store.ts",
    },
    {
      id: "capacity-transition.read.capacity_allocation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_allocation" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-hold-transition-store.ts",
    },
    {
      id: "capacity-transition.write.capacity_hold_terminal",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_hold_terminal" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: null,
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-hold-transition-store.ts",
    },
    {
      id: "capacity-transition.write.capacity_allocation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_allocation" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: null,
      source:
        "packages/rms/fulfillment/src/infrastructure/persistence/capacity-hold-transition-store.ts",
    },
    {
      id: "capacity-hold.read.capacity_slot",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_slot" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source: "packages/rms/fulfillment/src/infrastructure/persistence/capacity-hold-store.ts",
    },
    {
      id: "capacity-hold.read.capacity_hold",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_hold" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source: "packages/rms/fulfillment/src/infrastructure/persistence/capacity-hold-store.ts",
    },
    {
      id: "capacity-hold.write.capacity_hold",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_hold" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      source: "packages/rms/fulfillment/src/infrastructure/persistence/capacity-hold-store.ts",
    },
    {
      id: "capacity-query.read.capacity_slot",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_slot" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source: "packages/rms/fulfillment/src/infrastructure/persistence/capacity-query-store.ts",
    },
    {
      id: "capacity-query.read.capacity_hold",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_hold" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source: "packages/rms/fulfillment/src/infrastructure/persistence/capacity-query-store.ts",
    },
    {
      id: "capacity-query.read.capacity_hold_terminal",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_hold_terminal" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source: "packages/rms/fulfillment/src/infrastructure/persistence/capacity-query-store.ts",
    },
    {
      id: "capacity-query.read.capacity_allocation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_allocation" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source: "packages/rms/fulfillment/src/infrastructure/persistence/capacity-query-store.ts",
    },
    {
      id: "capacity-query.read.capacity_allocation_terminal",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_fulfillment", table: "capacity_allocation_terminal" },
      principal: { kind: "module", id: "@rms/fulfillment" },
      readPattern: "owner-repository",
      source: "packages/rms/fulfillment/src/infrastructure/persistence/capacity-query-store.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
export default databaseAccessManifest;
