// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "recipe",
    packageName: "@rms/recipe",
    layer: "RMS",
    lifecycle: "Later",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "effective-period",
        packageName: "@bop/effective-period",
        layer: "BOP",
      },
      {
        moduleName: "permission",
        packageName: "@bop/permission",
        layer: "BOP",
      },
      {
        moduleName: "tenant",
        packageName: "@bop/tenant",
        layer: "BOP",
      },
    ],
    consumedEvents: [],
    publishedEvents: [
      "rms.recipe.recipe-archived.v1",
      "rms.recipe.recipe-draft-created.v1",
      "rms.recipe.recipe-draft-replaced.v1",
      "rms.recipe.recipe-invalidated.v1",
      "rms.recipe.recipe-published.v1",
    ],
    ownedDatabase: {
      schema: "rms_recipe",
      tables: [
        "recipe",
        "recipe_version",
        "recipe_ingredient_requirement",
        "recipe_allergen_evidence",
        "recipe_preparation_step",
        "recipe_scope_binding",
        "recipe_review_record",
        "recipe_operation_record",
        "recipe_admin_projection_generation",
        "recipe_admin_projection",
        "recipe_admin_ingredient_projection",
        "recipe_admin_projection_checkpoint",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["none"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Recipe Engineering Owner",
    },
  } as const;

/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
