const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "identity", packageName: "@bop/identity", layer: "BOP" },
  tables: [
    {
      table: "api_client",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "api_client_access_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "api_client_credential_metadata",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "api_client_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "guest_session",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "authentication_session",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "sensitive_personal", "credential"],
    },
    {
      table: "oidc_authorization_transaction",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "session_revocation_request",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "sensitive_personal"],
    },
    {
      table: "workforce_invitation",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "personal", "credential"],
    },
    {
      table: "workforce_mfa_status",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "sensitive_personal"],
    },
    {
      table: "workforce_recovery_case",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "sensitive_personal"],
    },
  ],
  accesses: [
    {
      id: "guest-entry.touch-interactive",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "guest_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source: "packages/bop/identity/src/infrastructure/persistence/guest-session-entry-store.ts",
    },
    {
      id: "guest-entry.create",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "guest_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source: "packages/bop/identity/src/infrastructure/persistence/guest-session-entry-store.ts",
    },
    {
      id: "guest-entry.resolve",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "guest_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source: "packages/bop/identity/src/infrastructure/persistence/guest-session-entry-store.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
