const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "identity", packageName: "@bop/identity", layer: "BOP" },
  tables: [
    {
      table: "workforce_onboarding_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "workforce_account_binding",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "platform_actor_directory_head",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "platform_actor_directory_revision",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "browser_brand_session_selection",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "guest_entry_admission",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "browser_session_selection",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "guest_dining_binding_preparation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "guest_binding_preparation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "guest_session_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "api_client",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "api_client_access_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "api_client_credential_metadata",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "api_client_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "guest_session",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "authentication_session",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "sensitive_personal", "credential"],
    },
    {
      table: "oidc_authorization_transaction",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "credential"],
    },
    {
      table: "session_revocation_request",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "sensitive_personal"],
    },
    {
      table: "workforce_invitation",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "personal", "credential"],
    },
    {
      table: "workforce_mfa_status",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "sensitive_personal"],
    },
    {
      table: "workforce_recovery_case",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@bop/identity" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "privacy-governance",
      piiClassification: ["indirect_identifier", "sensitive_personal"],
    },
  ],
  accesses: [
    {
      id: "workforce-onboarding-invitation.workforce-onboarding-operation.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_onboarding_operation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/workforce-onboarding-invitation-source.ts",
    },
    {
      id: "workforce-onboarding-invitation.workforce-invitation.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_invitation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/workforce-onboarding-invitation-source.ts",
    },
    {
      id: "workforce-onboarding.workforce-onboarding-operation.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_onboarding_operation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/workforce-onboarding-operation-store.ts",
    },
    {
      id: "workforce-onboarding.workforce-onboarding-operation.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_onboarding_operation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source:
        "packages/bop/identity/src/infrastructure/persistence/workforce-onboarding-operation-store.ts",
    },
    {
      id: "workforce-onboarding.workforce-invitation.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_invitation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/workforce-onboarding-operation-store.ts",
    },
    {
      id: "workforce-invitation-store.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_invitation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source: "packages/bop/identity/src/infrastructure/persistence/workforce-invitation-store.ts",
    },
    {
      id: "workforce-invitation-store.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_invitation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source: "packages/bop/identity/src/infrastructure/persistence/workforce-invitation-store.ts",
    },
    {
      id: "workforce-account-binding-provisioner.read.binding",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_account_binding" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/workforce-account-binding-provisioner.ts",
    },
    {
      id: "workforce-account-binding-provisioner.write.binding",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_account_binding" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source:
        "packages/bop/identity/src/infrastructure/persistence/workforce-account-binding-provisioner.ts",
    },
    {
      id: "workforce-account-binding-provisioner.read.invitation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_invitation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/workforce-account-binding-provisioner.ts",
    },
    {
      id: "current-workforce-account.read.binding",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_account_binding" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/workforce-account-read-kernel.ts",
    },
    {
      id: "current-workforce-account.read.invitation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_invitation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/workforce-account-read-kernel.ts",
    },
    {
      id: "current-workforce-invitation.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_invitation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/current-workforce-invitation-source.ts",
    },
    {
      id: "platform-actor-directory-store.read.platform_actor_directory_head",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "platform_actor_directory_head" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/platform-actor-directory-store.ts",
    },
    {
      id: "platform-actor-directory-store.read.platform_actor_directory_revision",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "platform_actor_directory_revision" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/platform-actor-directory-store.ts",
    },
    {
      id: "platform-actor-directory-provisioner.read.platform_actor_directory_head",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "platform_actor_directory_head" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/platform-actor-directory-provisioner.ts",
    },
    {
      id: "platform-actor-directory-provisioner.write.platform_actor_directory_head",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "platform_actor_directory_head" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source:
        "packages/bop/identity/src/infrastructure/persistence/platform-actor-directory-provisioner.ts",
    },
    {
      id: "platform-actor-directory-provisioner.read.platform_actor_directory_revision",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "platform_actor_directory_revision" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/platform-actor-directory-provisioner.ts",
    },
    {
      id: "platform-actor-directory-provisioner.write.platform_actor_directory_revision",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "platform_actor_directory_revision" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source:
        "packages/bop/identity/src/infrastructure/persistence/platform-actor-directory-provisioner.ts",
    },
    {
      id: "platform-actor-directory-provisioner.read.authentication_session",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "authentication_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/platform-actor-directory-provisioner.ts",
    },
    {
      id: "platform-actor-directory-provisioner.write.authentication_session",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "authentication_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source:
        "packages/bop/identity/src/infrastructure/persistence/platform-actor-directory-provisioner.ts",
    },
    {
      id: "browser_brand_session_selection.read.authentication_session",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "authentication_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/browser-brand-session-selection-store.ts",
    },
    {
      id: "browser_brand_session_selection.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "browser_brand_session_selection" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/browser-brand-session-selection-store.ts",
    },
    {
      id: "browser_brand_session_selection.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "browser_brand_session_selection" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source:
        "packages/bop/identity/src/infrastructure/persistence/browser-brand-session-selection-store.ts",
    },
    {
      id: "guest-entry-admission.consume",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "guest_entry_admission" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source: "packages/bop/identity/src/infrastructure/persistence/guest-entry-admission-store.ts",
    },
    {
      id: "current-workforce-mfa.read",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "workforce_mfa_status" },
      principal: { kind: "module", id: "@bop/identity" },
      source:
        "packages/bop/identity/src/infrastructure/persistence/current-workforce-mfa-source.ts",
    },
    {
      id: "browser-session-selection.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "browser_session_selection" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source:
        "packages/bop/identity/src/infrastructure/persistence/browser-session-selection-store.ts",
    },
    {
      id: "browser-session-selection.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "browser_session_selection" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/browser-session-selection-store.ts",
    },
    {
      id: "browser-session.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "authentication_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source: "packages/bop/identity/src/infrastructure/persistence/browser-session-store.ts",
    },
    {
      id: "browser-session.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "authentication_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source: "packages/bop/identity/src/infrastructure/persistence/browser-session-store.ts",
    },
    {
      id: "oidc-authorization.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "oidc_authorization_transaction" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source: "packages/bop/identity/src/infrastructure/persistence/oidc-authorization-store.ts",
    },
    {
      id: "oidc-authorization.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "oidc_authorization_transaction" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source: "packages/bop/identity/src/infrastructure/persistence/oidc-authorization-store.ts",
    },
    {
      id: "current-browser-session.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "authentication_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source:
        "packages/bop/identity/src/infrastructure/persistence/current-browser-session-source.ts",
    },
    {
      id: "guest-session.legacy-inspection",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "guest_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source: "packages/bop/identity/src/infrastructure/persistence/guest-session-entry-store.ts",
    },
    {
      id: "guest-session.history-write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "guest_session_operation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source: "packages/bop/identity/src/infrastructure/persistence/guest-session-entry-store.ts",
    },
    {
      id: "guest-session.history-read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "guest_session_operation" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source: "packages/bop/identity/src/infrastructure/persistence/guest-session-entry-store.ts",
    },
    {
      id: "guest-entry.touch-interactive",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "guest_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source: "packages/bop/identity/src/infrastructure/persistence/guest-session-entry-store.ts",
    },
    {
      id: "guest-entry.create",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "guest_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: null,
      source: "packages/bop/identity/src/infrastructure/persistence/guest-session-entry-store.ts",
    },
    {
      id: "guest-entry.resolve",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_identity", table: "guest_session" },
      principal: { kind: "module", id: "@bop/identity" },
      readPattern: "owner-repository",
      source: "packages/bop/identity/src/infrastructure/persistence/guest-session-entry-store.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
