// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "public-capability",
    packageName: "@bop/public-capability",
    layer: "BOP",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [],
    consumedEvents: [],
    publishedEvents: [],
    ownedDatabase: {
      schema: null,
      tables: [],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["credential"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Public Capability Security Owner",
    },
  } as const;
/* module-manifest-json:end */

export const moduleManifest = defineModuleManifest(moduleManifestInput);
export default moduleManifest;
