// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import {
  defineModuleManifest,
  type ModuleManifest,
} from "../../../../tooling/module-manifest/module.manifest.js";
const moduleManifestInput: ModuleManifest =
  /* module-manifest-json:begin */
  {
    moduleName: "customer-loyalty",
    packageName: "@rms/customer-loyalty",
    layer: "RMS",
    lifecycle: "Later",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      { moduleName: "audit", packageName: "@bop/audit", layer: "BOP" },
    ],
    consumedEvents: [],
    publishedEvents: [],
    ownedDatabase: { schema: null, tables: [] },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier", "personal", "sensitive_personal"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: { role: "Customer & Loyalty Engineering Owner" },
  };
/* module-manifest-json:end */ export const moduleManifest =
  defineModuleManifest(moduleManifestInput);
export default moduleManifest;
