const databaseAccessManifestInput = {
  version: 1,
  module: {
    moduleName: "media",
    packageName: "@bop/media",
    layer: "BOP",
  },
  tables: [
    {
      table: "image_scan_admission",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/media" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "image_processing_intent",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/media" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "image_processing_completion",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/media" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "image_rendition",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/media" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "upload_object_binding",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/media" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "finalized_object_binding",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@bop/media" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "upload_session",
      classification: "aggregate-root",
      writeOwner: {
        kind: "module",
        id: "@bop/media",
      },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "asset",
      classification: "aggregate-root",
      writeOwner: {
        kind: "module",
        id: "@bop/media",
      },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "asset_version",
      classification: "immutable-snapshot",
      writeOwner: {
        kind: "module",
        id: "@bop/media",
      },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "operation_record",
      classification: "append-only-record",
      writeOwner: {
        kind: "module",
        id: "@bop/media",
      },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "media-publication-read.read.asset",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "asset" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-publication-read-store.ts",
    },
    {
      id: "media-publication-read.read.asset_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "asset_version" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-publication-read-store.ts",
    },
    {
      id: "media-publication-read.read.image_processing_intent",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_processing_intent" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-publication-read-store.ts",
    },
    {
      id: "media-publication-read.read.image_processing_completion",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_processing_completion" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-publication-read-store.ts",
    },
    {
      id: "media-publication-read.read.image_rendition",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_rendition" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-publication-read-store.ts",
    },
    {
      id: "media-publication-read.read.image_scan_admission",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_scan_admission" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-publication-read-store.ts",
    },
    {
      id: "media-publication-read.read.upload_object_binding",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "upload_object_binding" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-publication-read-store.ts",
    },

    {
      id: "media-image-scan-admission.read.image_scan_admission",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_scan_admission" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source:
        "packages/bop/media/src/infrastructure/persistence/media-image-scan-admission-store.ts",
    },
    {
      id: "media-image-scan-admission.write.image_scan_admission",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_scan_admission" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: null,
      source:
        "packages/bop/media/src/infrastructure/persistence/media-image-scan-admission-store.ts",
    },
    {
      id: "media-image-scan-admission.read.image_processing_intent",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_processing_intent" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source:
        "packages/bop/media/src/infrastructure/persistence/media-image-scan-admission-store.ts",
    },
    {
      id: "media-image-processing.store.read.asset_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "asset_version" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-store.ts",
    },
    {
      id: "media-image-processing.source.read.upload_session",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "upload_session" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-source.ts",
    },
    {
      id: "media-image-processing.source.read.asset",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "asset" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-source.ts",
    },
    {
      id: "media-image-processing.source.read.asset_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "asset_version" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-source.ts",
    },
    {
      id: "media-image-processing.source.read.operation_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "operation_record" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-source.ts",
    },
    {
      id: "media-image-processing.source.read.upload_object_binding",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "upload_object_binding" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-source.ts",
    },
    {
      id: "media-image-processing.source.read.finalized_object_binding",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "finalized_object_binding" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-source.ts",
    },
    {
      id: "media-image-processing.store.read.asset",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "asset" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-store.ts",
    },
    {
      id: "media-image-processing.store.read.image_processing_intent",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_processing_intent" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-store.ts",
    },
    {
      id: "media-image-processing.store.read.image_processing_completion",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_processing_completion" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-store.ts",
    },
    {
      id: "media-image-processing.store.read.image_rendition",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_rendition" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-store.ts",
    },
    {
      id: "media-image-processing.store.write.asset",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_media", table: "asset" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-store.ts",
    },
    {
      id: "media-image-processing.store.write.asset_version",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_media", table: "asset_version" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-store.ts",
    },
    {
      id: "media-image-processing.store.write.image_processing_intent",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_processing_intent" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-store.ts",
    },
    {
      id: "media-image-processing.store.write.image_processing_completion",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_processing_completion" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-store.ts",
    },
    {
      id: "media-image-processing.store.write.image_rendition",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_media", table: "image_rendition" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/media-image-processing-store.ts",
    },
    {
      id: "media-s3-upload.read.upload_session",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "upload_session" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/s3-image-upload-runtime.ts",
    },
    {
      id: "media-s3-upload.read.operation_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "operation_record" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/s3-image-upload-runtime.ts",
    },
    {
      id: "media-s3-upload.read.upload_object_binding",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "upload_object_binding" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/s3-image-upload-runtime.ts",
    },
    {
      id: "media-s3-upload.read.finalized_object_binding",
      operation: "read",
      mechanism: "repository",
      target: { schema: "bop_media", table: "finalized_object_binding" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/s3-image-upload-runtime.ts",
    },
    {
      id: "media-s3-upload.write.upload_object_binding",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_media", table: "upload_object_binding" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/s3-image-upload-runtime.ts",
    },
    {
      id: "media-s3-upload.write.finalized_object_binding",
      operation: "write",
      mechanism: "repository",
      target: { schema: "bop_media", table: "finalized_object_binding" },
      principal: { kind: "module", id: "@bop/media" },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/s3-image-upload-runtime.ts",
    },
    {
      id: "media-upload.read.upload_session",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "bop_media",
        table: "upload_session",
      },
      principal: {
        kind: "module",
        id: "@bop/media",
      },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-upload-store.ts",
    },
    {
      id: "media-upload.write.upload_session",
      operation: "write",
      mechanism: "repository",
      target: {
        schema: "bop_media",
        table: "upload_session",
      },
      principal: {
        kind: "module",
        id: "@bop/media",
      },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/media-upload-store.ts",
    },
    {
      id: "media-upload.read.asset",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "bop_media",
        table: "asset",
      },
      principal: {
        kind: "module",
        id: "@bop/media",
      },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-upload-store.ts",
    },
    {
      id: "media-upload.write.asset",
      operation: "write",
      mechanism: "repository",
      target: {
        schema: "bop_media",
        table: "asset",
      },
      principal: {
        kind: "module",
        id: "@bop/media",
      },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/media-upload-store.ts",
    },
    {
      id: "media-upload.read.asset_version",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "bop_media",
        table: "asset_version",
      },
      principal: {
        kind: "module",
        id: "@bop/media",
      },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-upload-store.ts",
    },
    {
      id: "media-upload.write.asset_version",
      operation: "write",
      mechanism: "repository",
      target: {
        schema: "bop_media",
        table: "asset_version",
      },
      principal: {
        kind: "module",
        id: "@bop/media",
      },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/media-upload-store.ts",
    },
    {
      id: "media-upload.read.operation_record",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "bop_media",
        table: "operation_record",
      },
      principal: {
        kind: "module",
        id: "@bop/media",
      },
      readPattern: "owner-repository",
      source: "packages/bop/media/src/infrastructure/persistence/media-upload-store.ts",
    },
    {
      id: "media-upload.write.operation_record",
      operation: "write",
      mechanism: "repository",
      target: {
        schema: "bop_media",
        table: "operation_record",
      },
      principal: {
        kind: "module",
        id: "@bop/media",
      },
      readPattern: null,
      source: "packages/bop/media/src/infrastructure/persistence/media-upload-store.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
export default databaseAccessManifest;
