import { lstat, mkdir, readFile, readdir, realpath, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve, sep } from "node:path";
import process from "node:process";
import { fileURLToPath, pathToFileURL, URL } from "node:url";
import { validateModuleManifest } from "../module-manifest/validate.mjs";

const generatorInputKeys = [
  "allowedDependencies",
  "databaseSchemaName",
  "layer",
  "moduleName",
  "owner",
  "packageName",
  "phase",
];

const canonicalDirectories = [
  "src/application/commands",
  "src/application/dto",
  "src/application/handlers",
  "src/application/ports",
  "src/application/queries",
  "src/contracts",
  "src/domain/aggregates",
  "src/domain/entities",
  "src/domain/errors",
  "src/domain/events",
  "src/domain/policies",
  "src/domain/services",
  "src/domain/value-objects",
  "src/infrastructure/jobs",
  "src/infrastructure/messaging",
  "src/infrastructure/persistence",
  "src/infrastructure/providers",
  "src/interfaces/consumers",
  "src/interfaces/http",
  "src/interfaces/realtime",
  "src/interfaces/webhook",
  "src/tests",
];

const manifestJsonStart = "/* module-manifest-json:begin */\n";
const manifestJsonEnd = "\n/* module-manifest-json:end */";
const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url));
const moduleReadmeTemplate = new URL("../../docs/templates/module/README.md", import.meta.url);

export const moduleGeneratorUsage = `BOP-RMS Module Generator

Usage:
  pnpm module-generator --input <generator-input.json>

Required JSON fields:
  layer                 BOP or RMS
  moduleName            unscoped kebab-case logical Module Name
  packageName           exactly @bop/<moduleName> or @rms/<moduleName>
  phase                 Phase 0, Phase 1, or Later
  allowedDependencies   Module identities accepted by the WP-0010 Manifest contract
  databaseSchemaName    future ownership metadata string or null; creates no database object
  owner                 accountable role supplied by the owning Work Package

The target is fixed to packages/bop/<moduleName> or packages/rms/<moduleName> in
this repository. Existing targets, partial targets, symlinks, case collisions,
unsafe paths, unknown fields, and invalid Manifest identities fail without overwrite.
`;

export class ModuleGeneratorError extends Error {
  constructor(message) {
    super(message);
    this.name = "ModuleGeneratorError";
  }
}

function sortDependencies(dependencies) {
  return [...dependencies].sort((left, right) =>
    left.packageName.localeCompare(right.packageName, "en"),
  );
}

export function buildModuleManifest(input) {
  if (!input || typeof input !== "object" || Array.isArray(input)) {
    throw new ModuleGeneratorError("generator input must be a JSON object");
  }

  const actualKeys = Object.keys(input).sort();
  const missingKeys = generatorInputKeys.filter((key) => !actualKeys.includes(key));
  const unknownKeys = actualKeys.filter((key) => !generatorInputKeys.includes(key));
  if (missingKeys.length > 0 || unknownKeys.length > 0) {
    const details = [
      missingKeys.length > 0 ? `missing fields: ${missingKeys.join(", ")}` : null,
      unknownKeys.length > 0 ? `unknown fields: ${unknownKeys.join(", ")}` : null,
    ].filter(Boolean);
    throw new ModuleGeneratorError(details.join("; "));
  }

  const manifest = {
    moduleName: input.moduleName,
    packageName: input.packageName,
    layer: input.layer,
    lifecycle: input.phase,
    publicExports: ["."],
    allowedSynchronousDependencies: input.allowedDependencies,
    consumedEvents: [],
    publishedEvents: [],
    ownedDatabase: { schema: input.databaseSchemaName, tables: [] },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["none"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: { role: input.owner },
  };

  const result = validateModuleManifest(manifest);
  if (!result.valid) {
    throw new ModuleGeneratorError(
      `input does not satisfy the WP-0010 Module Manifest contract:\n- ${result.errors.join("\n- ")}`,
    );
  }
  return {
    ...manifest,
    allowedSynchronousDependencies: sortDependencies(manifest.allowedSynchronousDependencies),
  };
}

function renderManifest(manifest) {
  const json = JSON.stringify(manifest, null, 2);
  return `// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput = ${manifestJsonStart}${json}${manifestJsonEnd};

export const moduleManifest = defineModuleManifest(moduleManifestInput);
export default moduleManifest;
`;
}

export function parseGeneratedManifestSource(source) {
  const start = source.indexOf(manifestJsonStart);
  const end = source.indexOf(manifestJsonEnd, start + manifestJsonStart.length);
  if (start < 0 || end < 0) {
    throw new ModuleGeneratorError("generated Manifest source is missing its validation payload");
  }
  return JSON.parse(source.slice(start + manifestJsonStart.length, end));
}

function renderPackageJson(manifest) {
  const dependencies = Object.fromEntries(
    manifest.allowedSynchronousDependencies.map((dependency) => [
      dependency.packageName,
      "workspace:*",
    ]),
  );
  const packageJson = {
    name: manifest.packageName,
    version: "0.0.0",
    private: true,
    type: "module",
    exports: { ".": { types: "./src/index.ts", import: "./src/index.ts" } },
    scripts: {
      build: "tsc --project tsconfig.json",
      "format:check": "prettier --check . --ignore-path ../../../.prettierignore",
      lint: "eslint src",
      test: "vitest run --passWithNoTests",
      typecheck: "tsc --project tsconfig.json",
    },
    ...(Object.keys(dependencies).length > 0 ? { dependencies } : {}),
  };
  return `${JSON.stringify(packageJson, null, 2)}\n`;
}

function renderTsconfig() {
  return `${JSON.stringify(
    {
      extends: "../../../tsconfig.base.json",
      compilerOptions: { lib: ["ES2024"], types: ["node"] },
      include: ["src/**/*.ts"],
    },
    null,
    2,
  )}\n`;
}

function markdownCode(value) {
  const encoded = JSON.stringify(value).slice(1, -1).replaceAll("`", "\\u0060");
  return `\`${encoded}\``;
}

async function renderReadme(manifest) {
  const template = await readFile(moduleReadmeTemplate, "utf8");
  return template
    .replace("# `<Module display name>`", `# \`${manifest.moduleName}\``)
    .replace("`<unscoped-kebab-case>`", `\`${manifest.moduleName}\``)
    .replace(
      "`<@bop/unscoped-kebab-case or @rms/unscoped-kebab-case>`",
      `\`${manifest.packageName}\``,
    )
    .replace("`<BOP or RMS / owning Domain>`", `\`${manifest.layer} / <owning Domain>\``)
    .replace("`<Phase / WP-xxxx>`", `\`${manifest.lifecycle} / <WP-xxxx>\``)
    .replace("`<role>`", markdownCode(manifest.moduleOwner.role))
    .replace("`<planned | active | deprecated>`", "`planned`");
}

async function pathState(path) {
  try {
    return await lstat(path);
  } catch (error) {
    if (error?.code === "ENOENT") return null;
    throw error;
  }
}

async function assertExactSegment(parent, segment) {
  const parentState = await pathState(parent);
  if (!parentState) return;
  if (parentState.isSymbolicLink() || !parentState.isDirectory()) {
    throw new ModuleGeneratorError(`unsafe path parent: ${parent}`);
  }
  const collision = (await readdir(parent)).find(
    (entry) => entry.toLowerCase() === segment.toLowerCase() && entry !== segment,
  );
  if (collision) {
    throw new ModuleGeneratorError(`case-insensitive path collision: ${join(parent, collision)}`);
  }
}

async function resolveSafeTarget(outputRoot, manifest) {
  const root = await realpath(outputRoot);
  const packagesRoot = join(root, "packages");
  const layerSegment = manifest.layer.toLowerCase();
  const layerRoot = join(packagesRoot, layerSegment);
  const target = join(layerRoot, manifest.moduleName);

  await assertExactSegment(root, "packages");
  const packagesState = await pathState(packagesRoot);
  if (!packagesState || packagesState.isSymbolicLink() || !packagesState.isDirectory()) {
    throw new ModuleGeneratorError("repository packages directory is missing or unsafe");
  }
  await assertExactSegment(packagesRoot, layerSegment);
  const layerState = await pathState(layerRoot);
  if (layerState?.isSymbolicLink() || (layerState && !layerState.isDirectory())) {
    throw new ModuleGeneratorError(`unsafe layer path: ${layerRoot}`);
  }
  await assertExactSegment(layerRoot, manifest.moduleName);

  const relativeTarget = relative(root, target);
  if (
    relativeTarget.startsWith(`..${sep}`) ||
    relativeTarget === ".." ||
    relativeTarget.startsWith(sep) ||
    relativeTarget !== join("packages", layerSegment, manifest.moduleName)
  ) {
    throw new ModuleGeneratorError("target path escapes the repository package boundary");
  }
  if (await pathState(target)) {
    throw new ModuleGeneratorError(`target already exists; refusing to overwrite: ${target}`);
  }
  return { layerRoot, target };
}

async function writeGeneratedTree(stagingRoot, manifest) {
  await Promise.all(
    canonicalDirectories.map((directory) =>
      mkdir(join(stagingRoot, directory), { recursive: true }),
    ),
  );
  const files = new Map([
    ["README.md", await renderReadme(manifest)],
    ["package.json", renderPackageJson(manifest)],
    ["tsconfig.json", renderTsconfig()],
    ["src/index.ts", 'export { moduleManifest } from "./module.manifest.js";\n'],
    ["src/module.manifest.ts", renderManifest(manifest)],
  ]);
  await Promise.all(
    [...files].map(async ([path, content]) => {
      const destination = join(stagingRoot, path);
      await mkdir(dirname(destination), { recursive: true });
      await writeFile(destination, content, { encoding: "utf8", flag: "wx", mode: 0o644 });
    }),
  );
}

export async function generateModule(input, { outputRoot = repositoryRoot } = {}) {
  const manifest = buildModuleManifest(input);
  const { layerRoot, target } = await resolveSafeTarget(outputRoot, manifest);
  await mkdir(layerRoot, { recursive: true });
  const layerState = await lstat(layerRoot);
  if (layerState.isSymbolicLink() || !layerState.isDirectory()) {
    throw new ModuleGeneratorError(`unsafe layer path after creation: ${layerRoot}`);
  }
  if ((await realpath(layerRoot)) !== layerRoot) {
    throw new ModuleGeneratorError(`layer path escapes through a symlink: ${layerRoot}`);
  }
  await assertExactSegment(layerRoot, manifest.moduleName);
  try {
    await mkdir(target, { recursive: false, mode: 0o755 });
  } catch (error) {
    if (error?.code === "EEXIST") {
      throw new ModuleGeneratorError(`target appeared during generation: ${target}`);
    }
    throw error;
  }
  try {
    await writeGeneratedTree(target, manifest);
  } catch (error) {
    await rm(target, { recursive: true, force: true });
    throw error;
  }
  return { manifest, target };
}

function parseCliArguments(arguments_) {
  if (arguments_.length === 1 && ["--help", "-h"].includes(arguments_[0])) return { help: true };
  if (arguments_.length !== 2 || arguments_[0] !== "--input") {
    throw new ModuleGeneratorError("expected exactly --input <generator-input.json>; use --help");
  }
  return { help: false, inputPath: resolve(process.cwd(), arguments_[1]) };
}

async function runCli() {
  const arguments_ = parseCliArguments(process.argv.slice(2));
  if (arguments_.help) {
    process.stdout.write(moduleGeneratorUsage);
    return;
  }
  const input = JSON.parse(await readFile(arguments_.inputPath, "utf8"));
  const result = await generateModule(input);
  process.stdout.write(`Created ${result.manifest.packageName} at ${result.target}\n`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  runCli().catch((error) => {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`Module Generator error: ${message}\n`);
    process.exitCode = 1;
  });
}
