const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "store", packageName: "@rms/store", layer: "RMS" },
  tables: [
    {
      table: "public_store_profile_timing",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },

    {
      table: "public_store_profile_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_configuration_review_snapshot",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },

    {
      table: "store_configuration_authoring_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_configuration_publication_content",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_service_pause_content",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_service_resume_content",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },

    {
      table: "store_service_exception_interval",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_service_exception_content",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_configuration_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_weekly_service_period",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_service_exception",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_configuration_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/store" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "public-store-profile-timing.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "public_store_profile_timing" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source:
        "packages/rms/store/src/infrastructure/persistence/public-store-profile-timing-store.ts",
    },
    {
      id: "public-store-profile-timing.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "public_store_profile_timing" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source:
        "packages/rms/store/src/infrastructure/persistence/public-store-profile-timing-store.ts",
    },
    {
      id: "public-store-profile.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "public_store_profile_version" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/public-store-profile-store.ts",
    },
    {
      id: "public-store-profile.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "public_store_profile_version" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/public-store-profile-store.ts",
    },

    {
      id: "review-snapshot.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_review_snapshot" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/review-snapshot-store.ts",
    },
    {
      id: "review-snapshot.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_review_snapshot" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/review-snapshot-store.ts",
    },

    {
      id: "business-date-authoring.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_authoring_operation" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/business-date-source.ts",
    },
    {
      id: "publication-materializer.store_configuration_version",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_version" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/publication-materializer.ts",
    },
    {
      id: "publication-materializer.store_weekly_service_period",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_weekly_service_period" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/publication-materializer.ts",
    },
    {
      id: "publication-materializer.store_service_exception",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_exception" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/publication-materializer.ts",
    },
    {
      id: "publication-materializer.store_service_exception_content",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_exception_content" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/publication-materializer.ts",
    },
    {
      id: "publication-materializer.store_service_exception_interval",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_exception_interval" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/publication-materializer.ts",
    },
    {
      id: "publication-materializer.store_configuration_publication_content",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_publication_content" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/publication-materializer.ts",
    },
    {
      id: "configuration-authoring.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_authoring_operation" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/configuration-authoring-store.ts",
    },
    {
      id: "configuration-authoring.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_authoring_operation" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/configuration-authoring-store.ts",
    },
    {
      id: "service-control.read.store_configuration_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_operation" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/service-control-store.ts",
    },
    {
      id: "service-control.write.store_configuration_operation",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_operation" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/service-control-store.ts",
    },
    {
      id: "service-control.read.store_service_pause_content",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_pause_content" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/service-control-store.ts",
    },
    {
      id: "service-control.write.store_service_pause_content",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_pause_content" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/service-control-store.ts",
    },
    {
      id: "service-control.read.store_service_resume_content",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_resume_content" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/service-control-store.ts",
    },
    {
      id: "service-control.write.store_service_resume_content",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_resume_content" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: null,
      source: "packages/rms/store/src/infrastructure/persistence/service-control-store.ts",
    },

    {
      id: "publication-content.read.store_configuration_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_version" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/publication-content-source.ts",
    },
    {
      id: "publication-content.read.store_configuration_publication_content",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_publication_content" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/publication-content-source.ts",
    },

    {
      id: "pause-history.read.store_configuration_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_operation" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/pause-history-source.ts",
    },
    {
      id: "pause-history.read.store_service_pause_content",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_pause_content" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/pause-history-source.ts",
    },
    {
      id: "pause-history.read.store_service_resume_content",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_resume_content" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/pause-history-source.ts",
    },

    {
      id: "weekly-schedule.read.store_configuration_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_version" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/weekly-schedule-source.ts",
    },
    {
      id: "weekly-schedule.read.store_weekly_service_period",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_weekly_service_period" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/weekly-schedule-source.ts",
    },

    {
      id: "exception-content.read.store_service_exception_interval",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_exception_interval" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/exception-content-source.ts",
    },
    {
      id: "exception-content.read.store_service_exception_content",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_exception_content" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/exception-content-source.ts",
    },
    {
      id: "exception-content.read.store_service_exception",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_service_exception" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/exception-content-source.ts",
    },
    {
      id: "exception-content.read.store_configuration_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_version" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/exception-content-source.ts",
    },
    {
      id: "merchant-business-date.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_store", table: "store_configuration_version" },
      principal: { kind: "module", id: "@rms/store" },
      readPattern: "owner-repository",
      source: "packages/rms/store/src/infrastructure/persistence/business-date-source.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
export default databaseAccessManifest;
