const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "inventory", packageName: "@rms/inventory", layer: "RMS" },
  tables: [
    {
      table: "stock_site",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "stock_site_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "storage_location",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "storage_location_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "stock_place_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "item_sku_mapping_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "configuration_reference_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/inventory.configuration-reference.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "submission_final_validation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "stock_reservation_set",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "stock_lot_hold_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "stock_reservation_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "stock_movement",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "stock_balance",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "stock_account",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "transactional",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "inventory_item",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "inventory_item_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "stock_lot",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "opening_count",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "opening_count_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "opening_count_posting",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_receipt",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_receipt_void",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "item_stock_exposure",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["none"],
    },
    {
      table: "inventory_item_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_configuration_source_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_configuration_source_capture",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/inventory" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "inventory-recipe-ingredient-units.read.inventory_item_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item_version" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/recipe-ingredient-unit-source-store.ts",
    },
    {
      id: "inventory-recipe-ingredient-units.read.inventory_item_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item_operation" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/recipe-ingredient-unit-source-store.ts",
    },
    {
      id: "inventory-option-consumption-units.read.inventory_item_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item_version" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/option-consumption-unit-source-store.ts",
    },
    {
      id: "inventory-option-consumption-units.read.inventory_item_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item_operation" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/option-consumption-unit-source-store.ts",
    },
    {
      id: "inventory-sku-mapping-store.read.inventory_item",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/inventory-sku-mapping-store.ts",
    },
    {
      id: "inventory-sku-mapping-store.read.inventory_item_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item_version" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/inventory-sku-mapping-store.ts",
    },
    {
      id: "inventory-sku-mapping-store.read.inventory_item_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item_operation" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/inventory-sku-mapping-store.ts",
    },
    {
      id: "inventory-sku-mapping-store.read.item_sku_mapping_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "item_sku_mapping_version" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/inventory-sku-mapping-store.ts",
    },
    {
      id: "sku-mapping-reference-source-store.read.item_sku_mapping_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "item_sku_mapping_version" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/sku-mapping-reference-source-store.ts",
    },
    {
      id: "sku-mapping-reference-source-store.read.configuration_reference_generation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "configuration_reference_generation" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/sku-mapping-reference-source-store.ts",
    },
    {
      id: "inventory-sku-mapping.write.item_sku_mapping_version",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "item_sku_mapping_version" },
      principal: { kind: "module", id: "@rms/inventory" },
      source:
        "packages/rms/inventory/src/infrastructure/persistence/inventory-sku-mapping-store.ts",
    },
    {
      id: "inventory-configuration-reference.read.inventory_item",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/configuration-reference-source-store.ts",
    },
    {
      id: "inventory-configuration-reference.read.inventory_item_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item_version" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/configuration-reference-source-store.ts",
    },
    {
      id: "inventory-configuration-reference.read.inventory_item_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item_operation" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/configuration-reference-source-store.ts",
    },
    {
      id: "inventory-configuration-reference.read.configuration_reference_generation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "configuration_reference_generation" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/configuration-reference-source-store.ts",
    },
    {
      id: "inventory-item-store.read.item_stock_exposure",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "item_stock_exposure" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/inventory-item-store.ts",
    },
    {
      id: "stock-place-store.read.stock_account",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_account" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/stock-place-store.ts",
    },
    {
      id: "stock-place-store.read.stock_balance",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_balance" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/stock-place-store.ts",
    },
    {
      id: "opening-count-store.read.opening_count_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "opening_count_version" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.read.opening_count_posting",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "opening_count_posting" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.read.stock_lot",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_lot" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.read.stock_account",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_account" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.read.stock_balance",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_balance" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.write.opening_count",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "opening_count" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.write.opening_count_version",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "opening_count_version" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.write.opening_count_posting",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "opening_count_posting" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.write.stock_lot",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_lot" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.write.stock_account",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_account" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.write.stock_balance",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_balance" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "opening-count-store.write.stock_movement",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_movement" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/opening-count-store.ts",
    },
    {
      id: "ledger-posting.read.stock_lot",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_lot" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/ledger-posting.ts",
    },
    {
      id: "ledger-posting.read.stock_account",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_account" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/ledger-posting.ts",
    },
    {
      id: "ledger-posting.read.stock_balance",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_balance" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/ledger-posting.ts",
    },
    {
      id: "ledger-posting.write.stock_lot",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_lot" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/ledger-posting.ts",
    },
    {
      id: "ledger-posting.write.stock_account",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_account" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/ledger-posting.ts",
    },
    {
      id: "ledger-posting.write.stock_balance",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_balance" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/ledger-posting.ts",
    },
    {
      id: "ledger-posting.write.stock_movement",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_movement" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/ledger-posting.ts",
    },
    {
      id: "inventory-recipe-facts.read.inventory_item",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/inventory-recipe-facts-store.ts",
    },
    {
      id: "inventory-recipe-facts.read.inventory_item_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item_version" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/inventory-recipe-facts-store.ts",
    },
    {
      id: "inventory-recipe-facts.read.inventory_item_operation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "inventory_item_operation" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/inventory-recipe-facts-store.ts",
    },
    {
      id: "inventory-recipe-facts.read.stock_movement",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_movement" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source:
        "packages/rms/inventory/src/infrastructure/persistence/inventory-recipe-facts-store.ts",
    },
    {
      id: "store-receipt-store.read.store_receipt",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "store_receipt" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/store-receipt-store.ts",
    },
    {
      id: "store-receipt-store.read.store_receipt_void",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "store_receipt_void" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/store-receipt-store.ts",
    },
    {
      id: "store-receipt-store.read.stock_movement",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_movement" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/store-receipt-store.ts",
    },
    {
      id: "store-receipt-store.read.stock_account",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_account" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/store-receipt-store.ts",
    },
    {
      id: "store-receipt-store.read.stock_balance",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "stock_balance" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: "owner-repository",
      source: "packages/rms/inventory/src/infrastructure/persistence/store-receipt-store.ts",
    },
    {
      id: "store-receipt-store.write.store_receipt",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "store_receipt" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/store-receipt-store.ts",
    },
    {
      id: "store-receipt-store.write.store_receipt_void",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_inventory", table: "store_receipt_void" },
      principal: { kind: "module", id: "@rms/inventory" },
      readPattern: null,
      source: "packages/rms/inventory/src/infrastructure/persistence/store-receipt-store.ts",
    },
  ],
} as const;
export default databaseAccessManifestInput;
