// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "business-intelligence",
    packageName: "@rms/business-intelligence",
    layer: "RMS",
    lifecycle: "Later",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "permission",
        packageName: "@bop/permission",
        layer: "BOP",
      },
      {
        moduleName: "publishing",
        packageName: "@bop/publishing",
        layer: "BOP",
      },
      {
        moduleName: "tenant",
        packageName: "@bop/tenant",
        layer: "BOP",
      },
    ],
    consumedEvents: [],
    publishedEvents: [
      "rms.business-intelligence.report-artifact-revision-recorded.v1",
      "rms.business-intelligence.report-artifact-revoked.v1",
      "rms.business-intelligence.report-definition-archived.v1",
      "rms.business-intelligence.report-definition-draft-created.v1",
      "rms.business-intelligence.report-definition-draft-replaced.v1",
      "rms.business-intelligence.report-definition-published.v1",
      "rms.business-intelligence.report-definition-review-submitted.v1",
      "rms.business-intelligence.report-run-queued.v1",
      "rms.business-intelligence.report-run-state-recorded.v1",
      "rms.business-intelligence.report-schedule-version-recorded.v1",
    ],
    ownedDatabase: {
      schema: "rms_reporting",
      tables: [
        "report_definition",
        "report_version",
        "report_dataset_reference",
        "report_metric_reference",
        "report_dimension",
        "report_filter",
        "report_sort",
        "report_operation_record",
        "report_schedule",
        "report_schedule_version",
        "report_schedule_operation_record",
        "report_run",
        "report_run_metric_reference",
        "report_run_state_record",
        "report_artifact",
        "report_artifact_revision",
        "report_artifact_revocation",
        "report_run_operation_record",
        "report_artifact_download_record",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Business Intelligence Engineering Owner",
    },
  } /* module-manifest-json:end */ as const;

export const moduleManifest = defineModuleManifest(moduleManifestInput);
export default moduleManifest;
