// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "kitchen",
    packageName: "@rms/kitchen",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "eventing",
        packageName: "@bop/eventing",
        layer: "BOP",
      },
      {
        moduleName: "ordering",
        packageName: "@rms/ordering",
        layer: "RMS",
      },
    ],
    consumedEvents: ["rms.kitchen.kitchen-work-created.v1", "rms.ordering.order-confirmed.v1"],
    publishedEvents: ["rms.kitchen.kitchen-work-created.v1"],
    ownedDatabase: {
      schema: "rms_kitchen",
      tables: [
        "kitchen_action_record",
        "kitchen_ticket",
        "kitchen_work_item",
        "kitchen_work_queue_projection",
        "kitchen_work_queue_projection_generation",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier", "personal", "health"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Kitchen Engineering Owner",
    },
  } as const;
/* module-manifest-json:end */

export const moduleManifest = defineModuleManifest(moduleManifestInput);
export default moduleManifest;
