// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import { defineModuleManifest } from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput =
  /* module-manifest-json:begin */
  {
    moduleName: "kitchen",
    packageName: "@rms/kitchen",
    layer: "RMS",
    lifecycle: "Phase 1",
    publicExports: ["."],
    allowedSynchronousDependencies: [
      {
        moduleName: "audit",
        packageName: "@bop/audit",
        layer: "BOP",
      },
      {
        moduleName: "eventing",
        packageName: "@bop/eventing",
        layer: "BOP",
      },
      {
        moduleName: "ordering",
        packageName: "@rms/ordering",
        layer: "RMS",
      },
    ],
    consumedEvents: [
      "rms.kitchen.kitchen-item-completed.v1",
      "rms.kitchen.kitchen-item-progress-recorded.v1",
      "rms.kitchen.kitchen-work-accepted.v1",
      "rms.kitchen.kitchen-work-created.v1",
      "rms.kitchen.kitchen-work-started.v1",
      "rms.ordering.order-confirmed.v1",
    ],
    publishedEvents: [
      "rms.kitchen.kitchen-item-completed.v1",
      "rms.kitchen.kitchen-item-progress-recorded.v1",
      "rms.kitchen.kitchen-item-ready.v1",
      "rms.kitchen.kitchen-order-ready.v1",
      "rms.kitchen.kitchen-work-accepted.v1",
      "rms.kitchen.kitchen-work-created.v1",
      "rms.kitchen.kitchen-work-started.v1",
    ],
    ownedDatabase: {
      schema: "rms_kitchen",
      tables: [
        "kds_operator_handover",
        "kds_recovery_reconciliation",
        "kitchen_allergen_acknowledgement",
        "kitchen_allergen_incident_link",
        "kitchen_allergen_review",
        "kitchen_action_record",
        "kitchen_order_item_ready_result",
        "kitchen_ready_publication",
        "kitchen_ticket",
        "kitchen_work_item",
        "kitchen_work_lifecycle_operation",
        "kitchen_work_queue_projection",
        "kitchen_work_queue_projection_generation",
      ],
    },
    ownedJobs: [],
    featureFlags: [],
    killSwitches: [],
    piiClassification: {
      classes: ["indirect_identifier", "personal", "health"],
      handling: {
        logs: "prohibited",
        urls: "prohibited",
        analytics: "prohibited",
        fixtures: "synthetic-only",
      },
    },
    moduleOwner: {
      role: "Kitchen Engineering Owner",
    },
  } as const;
/* module-manifest-json:end */

export const moduleManifest = defineModuleManifest(moduleManifestInput);
export default moduleManifest;
