// Generated by the BOP-RMS Module Generator. Do not add private exports here.
import {
  defineModuleManifest,
  type ModuleManifest,
} from "../../../../tooling/module-manifest/module.manifest.js";

const moduleManifestInput = JSON.parse(String.raw`/* module-manifest-json:begin */
{
  "moduleName": "membership",
  "packageName": "@bop/membership",
  "layer": "BOP",
  "lifecycle": "Phase 0",
  "publicExports": [
    "."
  ],
  "allowedSynchronousDependencies": [
    {
      "moduleName": "identity",
      "packageName": "@bop/identity",
      "layer": "BOP"
    },
    {
      "moduleName": "tenant",
      "packageName": "@bop/tenant",
      "layer": "BOP"
    }
  ],
  "consumedEvents": [],
  "publishedEvents": [],
  "ownedDatabase": {
    "schema": "bop_membership",
    "tables": [
      "membership",
      "store_assignment"
    ]
  },
  "ownedJobs": [],
  "featureFlags": [],
  "killSwitches": [],
  "piiClassification": {
    "classes": [
      "indirect_identifier",
      "sensitive_personal"
    ],
    "handling": {
      "logs": "prohibited",
      "urls": "prohibited",
      "analytics": "prohibited",
      "fixtures": "synthetic-only"
    }
  },
  "moduleOwner": {
    "role": "Membership Engineering Owner"
  }
}
/* module-manifest-json:end */`) as ModuleManifest;

export const moduleManifest = defineModuleManifest(moduleManifestInput);
export default moduleManifest;
