const databaseAccessManifestInput = {
  version: 1,
  module: {
    moduleName: "business-intelligence",
    packageName: "@rms/business-intelligence",
    layer: "RMS",
  },
  tables: [
    {
      table: "backfill_request",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "backfill_request_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "data_quality_check",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "data_quality_check_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "data_quality_result",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "data_quality_issue_action",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "reconciliation_run",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "reconciliation_exception_state",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "data_quality_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_definition",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_dimension",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_required_filter",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_inclusion_rule",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_exclusion_rule",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_dataset_reference",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_transformation_reference",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_dependency_reference",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_certification_evidence",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "metric_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "pipeline_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "pipeline_run",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "pipeline_run_state",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_definition",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_dataset_reference",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_metric_reference",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_dimension",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_filter",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_sort",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_schedule",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_schedule_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_schedule_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_run",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_run_metric_reference",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_run_state_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_artifact",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_artifact_revision",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_artifact_revocation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_run_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_artifact_download_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
