const databaseAccessManifestInput = {
  version: 1,
  module: {
    moduleName: "business-intelligence",
    packageName: "@rms/business-intelligence",
    layer: "RMS",
  },
  tables: [
    {
      table: "report_definition",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_dataset_reference",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_metric_reference",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_dimension",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_filter",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_sort",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_schedule",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_schedule_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "report_schedule_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/business-intelligence" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
