const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "payment", packageName: "@rms/payment", layer: "RMS" },
  tables: [
    {
      table: "store_payment_configuration_version",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "store_payment_configuration_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "reconciliation_follow_up_history",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "provider_capture_exception_evidence",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "order_settled_finality",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "ordinary_refund_observation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "ordinary_refund_dispatch",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "ordinary_refund_operation",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "ordinary_refund_approval",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "ordinary_refund_request",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_compensation_operations",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_compensation_refund",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_compensation_action_history",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },

    {
      table: "payment_compensation_case_history",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_compensation_operation_history",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_compensation_lease_history",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_tip_selection",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_intent",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_attempt",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_intent_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_provider_observation",
      classification: "integration-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "provider_webhook_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "provider_webhook_raw_evidence",
      classification: "integration-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "provider_webhook_processing_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_terminal_fact",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_refund_status_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/payment.status.v1" },
      allowedReadPatterns: ["public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_status_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/payment.status.v1" },
      allowedReadPatterns: ["public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_reconciliation_run",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_reconciliation_exception",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
    {
      table: "payment_reconciliation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/payment" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "financial-compliance",
      piiClassification: ["indirect_identifier", "payment"],
    },
  ],
  accesses: [
    {
      id: "ordinary-refund-capture.read.payment_intent",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_intent" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-capture-source.ts",
    },
    {
      id: "ordinary-refund-capture.read.payment_provider_observation",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_provider_observation" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-capture-source.ts",
    },
    {
      id: "ordinary-refund-observation.read",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "ordinary_refund_observation" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-operation-store.ts",
    },
    {
      id: "ordinary-refund-observation.write",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: { schema: "rms_payment", table: "ordinary_refund_observation" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-operation-store.ts",
    },
    {
      id: "ordinary-refund-dispatch.read",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "ordinary_refund_dispatch" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-operation-store.ts",
    },
    {
      id: "ordinary-refund-dispatch.write",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: { schema: "rms_payment", table: "ordinary_refund_dispatch" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-operation-store.ts",
    },
    {
      id: "ordinary-refund-operation.read",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "ordinary_refund_operation" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-operation-store.ts",
    },
    {
      id: "ordinary-refund-operation.write",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: { schema: "rms_payment", table: "ordinary_refund_operation" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-operation-store.ts",
    },
    {
      id: "ordinary-refund-approval.read",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "ordinary_refund_approval" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-approval-store.ts",
    },
    {
      id: "ordinary-refund-approval.write",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: { schema: "rms_payment", table: "ordinary_refund_approval" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-approval-store.ts",
    },
    {
      id: "ordinary-refund-request.read",
      operation: "read",
      readPattern: "owner-repository",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "ordinary_refund_request" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-request-store.ts",
    },
    {
      id: "ordinary-refund-request.write",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: { schema: "rms_payment", table: "ordinary_refund_request" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/ordinary-refund-request-store.ts",
    },
    {
      id: "payment-receipt-coverage-source.read.payment_intent",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_intent" },
      principal: { kind: "module", id: "@rms/payment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-receipt-coverage-source.ts",
    },
    {
      id: "payment-receipt-coverage-source.read.payment_provider_observation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_provider_observation" },
      principal: { kind: "module", id: "@rms/payment" },
      readPattern: "owner-repository",
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-receipt-coverage-source.ts",
    },
    {
      id: "payment-refund-status-store.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_refund_status_projection" },
      principal: { kind: "projection-builder", id: "@rms/payment.status.v1" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-refund-status-store.ts",
      readPattern: "public-query-contract",
    },
    {
      id: "payment-status-store.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_status_projection" },
      principal: { kind: "projection-builder", id: "@rms/payment.status.v1" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-status-store.ts",
      readPattern: "public-query-contract",
    },
    {
      id: "payment-refund-status-store.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_refund_status_projection" },
      principal: { kind: "projection-builder", id: "@rms/payment.status.v1" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-refund-status-store.ts",
      readPattern: null,
    },
    {
      id: "payment-status-store.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_status_projection" },
      principal: { kind: "projection-builder", id: "@rms/payment.status.v1" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-status-store.ts",
      readPattern: null,
    },

    {
      id: "payment-provider-observation-store.write",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_provider_observation" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-provider-observation-store.ts",
      readPattern: null,
    },
    {
      id: "payment-provider-observation-store.read",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_provider_observation" },
      principal: { kind: "module", id: "@rms/payment" },
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-provider-observation-store.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-terminal-store.read.payment_terminal_fact",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_terminal_fact" },
      principal: { kind: "module", id: "@rms/payment" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-terminal-store.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-terminal-store.write.payment_terminal_fact",
      operation: "write",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_terminal_fact" },
      principal: { kind: "module", id: "@rms/payment" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-terminal-store.ts",
      readPattern: null,
    },
    {
      id: "payment-terminal-store.read.payment_intent",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_intent" },
      principal: { kind: "module", id: "@rms/payment" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-terminal-store.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-terminal-source.read.payment_intent",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_intent" },
      principal: { kind: "module", id: "@rms/payment" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-terminal-source.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-terminal-source.read.payment_attempt",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_attempt" },
      principal: { kind: "module", id: "@rms/payment" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-terminal-source.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-terminal-source.read.payment_provider_observation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "payment_provider_observation" },
      principal: { kind: "module", id: "@rms/payment" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-terminal-source.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-terminal-source.read.provider_webhook_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_payment", table: "provider_webhook_record" },
      principal: { kind: "module", id: "@rms/payment" },
      source: "packages/rms/payment/src/infrastructure/persistence/payment-terminal-source.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-intent-store.read.payment_intent",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "rms_payment",
        table: "payment_intent",
      },
      principal: {
        kind: "module",
        id: "@rms/payment",
      },
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-intent-creation-store.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-intent-store.write.payment_intent",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: {
        schema: "rms_payment",
        table: "payment_intent",
      },
      principal: {
        kind: "module",
        id: "@rms/payment",
      },
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-intent-creation-store.ts",
    },
    {
      id: "payment-intent-store.read.payment_attempt",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "rms_payment",
        table: "payment_attempt",
      },
      principal: {
        kind: "module",
        id: "@rms/payment",
      },
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-intent-creation-store.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-intent-store.write.payment_attempt",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: {
        schema: "rms_payment",
        table: "payment_attempt",
      },
      principal: {
        kind: "module",
        id: "@rms/payment",
      },
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-intent-creation-store.ts",
    },
    {
      id: "payment-intent-store.read.payment_intent_operation_record",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "rms_payment",
        table: "payment_intent_operation_record",
      },
      principal: {
        kind: "module",
        id: "@rms/payment",
      },
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-intent-creation-store.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-intent-store.write.payment_intent_operation_record",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: {
        schema: "rms_payment",
        table: "payment_intent_operation_record",
      },
      principal: {
        kind: "module",
        id: "@rms/payment",
      },
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-intent-creation-store.ts",
    },
    {
      id: "payment-intent-store.read.payment_provider_observation",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "rms_payment",
        table: "payment_provider_observation",
      },
      principal: {
        kind: "module",
        id: "@rms/payment",
      },
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-intent-creation-store.ts",
      readPattern: "owner-repository",
    },
    {
      id: "payment-intent-store.write.payment_provider_observation",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: {
        schema: "rms_payment",
        table: "payment_provider_observation",
      },
      principal: {
        kind: "module",
        id: "@rms/payment",
      },
      source:
        "packages/rms/payment/src/infrastructure/persistence/payment-intent-creation-store.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
export default databaseAccessManifest;
