const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "recipe", packageName: "@rms/recipe", layer: "RMS" },
  tables: [
    {
      table: "recipe_measurement_content",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_reference_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.catalog-reference.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_reference_binding",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.catalog-reference.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_preparation_content",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier", "personal"],
    },
    {
      table: "recipe_modifier_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_ingredient_requirement",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_allergen_evidence",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_preparation_step",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_scope_binding",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_review_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_ingredient_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_projection_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_core_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v2" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_core_row",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v2" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_core_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v2" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_source_capture",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_source_binding",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v2" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_source_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v2" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_source_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v2" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [
    {
      id: "recipe-measurement-draft.read.recipe_measurement_content",
      operation: "read",
      mechanism: "repository",
      target: {
        schema: "rms_recipe",
        table: "recipe_measurement_content",
      },
      principal: {
        kind: "module",
        id: "@rms/recipe",
      },
      source:
        "packages/rms/recipe/src/infrastructure/persistence/recipe-measurement-draft-store.ts",
      readPattern: "owner-repository",
    },
    {
      id: "recipe-measurement-draft.write.recipe_measurement_content",
      operation: "write",
      readPattern: null,
      mechanism: "repository",
      target: {
        schema: "rms_recipe",
        table: "recipe_measurement_content",
      },
      principal: {
        kind: "module",
        id: "@rms/recipe",
      },
      source:
        "packages/rms/recipe/src/infrastructure/persistence/recipe-measurement-draft-store.ts",
    },
    {
      id: "recipe-pinned-subrecipe-graph.read.recipe_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_version" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/current-published-recipe-dependency-graph-source.ts",
    },
    {
      id: "recipe-pinned-subrecipe-graph.read.recipe_operation_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_operation_record" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/current-published-recipe-dependency-graph-source.ts",
    },
    {
      id: "recipe-pinned-subrecipe-graph.read.recipe_review_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_review_record" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/current-published-recipe-dependency-graph-source.ts",
    },
    {
      id: "recipe-current-published-content.read.recipe_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_version" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/current-published-recipe-content-source.ts",
    },
    {
      id: "recipe-current-published-content.read.recipe_operation_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_operation_record" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/current-published-recipe-content-source.ts",
    },
    {
      id: "recipe-current-published-content.read.recipe_review_record",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_review_record" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/current-published-recipe-content-source.ts",
    },
    {
      id: "recipe-option-consumption-yields.read.recipe_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_version" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/option-consumption-yield-source-store.ts",
    },
    {
      id: "recipe-inventory-reference.read.recipe",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/recipe-inventory-reference-source-store.ts",
    },
    {
      id: "recipe-inventory-reference.read.recipe_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_version" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/recipe-inventory-reference-source-store.ts",
    },
    {
      id: "recipe-inventory-reference.read.recipe_ingredient_requirement",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_ingredient_requirement" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/recipe-inventory-reference-source-store.ts",
    },
    {
      id: "recipe-inventory-reference.read.recipe_modifier_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_modifier_version" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/recipe-inventory-reference-source-store.ts",
    },
    {
      id: "recipe-inventory-reference.read.recipe_reference_generation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_reference_generation" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source:
        "packages/rms/recipe/src/infrastructure/persistence/recipe-inventory-reference-source-store.ts",
    },

    {
      id: "recipe-reference.read.recipe",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source: "packages/rms/recipe/src/infrastructure/persistence/recipe-reference-source-store.ts",
    },
    {
      id: "recipe-reference.read.recipe_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_version" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source: "packages/rms/recipe/src/infrastructure/persistence/recipe-reference-source-store.ts",
    },
    {
      id: "recipe-reference.read.recipe_modifier_version",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_modifier_version" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source: "packages/rms/recipe/src/infrastructure/persistence/recipe-reference-source-store.ts",
    },
    {
      id: "recipe-reference.read.recipe_reference_generation",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_reference_generation" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source: "packages/rms/recipe/src/infrastructure/persistence/recipe-reference-source-store.ts",
    },
    {
      id: "recipe-reference.read.recipe_reference_binding",
      operation: "read",
      mechanism: "repository",
      target: { schema: "rms_recipe", table: "recipe_reference_binding" },
      principal: { kind: "module", id: "@rms/recipe" },
      readPattern: "owner-repository",
      source: "packages/rms/recipe/src/infrastructure/persistence/recipe-reference-source-store.ts",
    },
  ],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
