const databaseAccessManifestInput = {
  version: 1,
  module: { moduleName: "recipe", packageName: "@rms/recipe", layer: "RMS" },
  tables: [
    {
      table: "recipe",
      classification: "aggregate-root",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_version",
      classification: "configuration-version",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_ingredient_requirement",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_allergen_evidence",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_preparation_step",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_scope_binding",
      classification: "aggregate-child-entity",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_review_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_operation_record",
      classification: "append-only-record",
      writeOwner: { kind: "module", id: "@rms/recipe" },
      allowedReadPatterns: ["owner-repository"],
      retentionCategory: "audit-security",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_projection_generation",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_ingredient_projection",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
    {
      table: "recipe_admin_projection_checkpoint",
      classification: "projection-read-model",
      writeOwner: { kind: "projection-builder", id: "@rms/recipe.admin.v1" },
      allowedReadPatterns: ["owner-repository", "public-query-contract"],
      retentionCategory: "operational",
      piiClassification: ["indirect_identifier"],
    },
  ],
  accesses: [],
} as const;

export const databaseAccessManifest = databaseAccessManifestInput;
